@extends('layouts.app')
@section('title','Departments')
@section('page-header')
<div class="container-fluid"><div class="row g-2 align-items-center"><div class="col"><div class="page-pretitle">Administrator</div><h2 class="page-title">Departments</h2></div><div class="col-auto"><button class="btn btn-primary" id="btnNewDepartment"><i class="ti ti-plus icon"></i> New Department</button></div></div></div>
@endsection
@section('content')
<style>
#departmentModal .modal-dialog{max-width:420px}
#departmentModal .department-field{position:relative;margin-bottom:1rem}
#departmentModal .department-field>.form-label{position:absolute;z-index:2;top:1rem;left:1rem;margin:0;padding:0 .35rem;background:transparent;color:var(--tblr-secondary);font-size:.95rem;font-weight:400;line-height:1.1;pointer-events:none;transition:top .16s ease,font-size .16s ease,color .16s ease,background-color .16s ease}
#departmentModal .department-field.has-value>.form-label,#departmentModal .department-field:focus-within>.form-label{top:.42rem;padding:0 .45rem;background:var(--tblr-bg-surface,#fff);color:#5b4bd1;font-size:.72rem;font-weight:700}
#departmentModal .department-field>.form-control{height:52px;min-height:52px;padding:1.25rem 1rem .35rem;border:1.5px solid #dfe3ea;border-radius:14px;background:var(--tblr-bg-forms,#fff);color:var(--tblr-body-color);box-shadow:0 2px 7px rgba(31,41,55,.04)}
#departmentModal .department-status-row{display:flex;justify-content:flex-end;margin:1rem 0;min-height:30px}
[data-bs-theme="dark"] #departmentModal .department-field.has-value>.form-label,[data-bs-theme="dark"] #departmentModal .department-field:focus-within>.form-label{background:#1e293b;color:#a99cff}
[data-bs-theme="dark"] #departmentModal .department-field>.form-control{background:#1e293b!important;color:#f8fafc!important;border-color:#475569!important}
</style>
@php($departmentStatus = old('status', $editDepartment?->status ?? 1))
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif @if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
<div class="card"><div class="card-header"><h3 class="card-title">Department Lists</h3></div><form method="GET"><div class="card-body border-bottom py-3"><div class="row justify-content-between"><div class="col-auto text-secondary">Show <select class="form-select form-select-sm d-inline-block w-auto mx-2" name="per_page" onchange="this.form.submit()"><option value="10" @selected(request('per_page',10)==10)>10 / page</option><option value="25" @selected(request('per_page')==25)>25 / page</option><option value="50" @selected(request('per_page')==50)>50 / page</option></select> entries</div><div class="col-auto input-icon"><span class="input-icon-addon"><i class="ti ti-search"></i></span><input class="form-control form-control-sm" name="search" value="{{ request('search') }}" placeholder="Search departments"></div></div></div></form><div class="table-responsive table-vcenter text-nowrap"><table class="table card-table"><thead><tr><th>No.</th><th>Department</th><th>Code</th><th>Status</th><th class="text-center">Actions</th></tr></thead><tbody>@forelse($departments as $department)<tr><td>{{ $departments->firstItem()+$loop->index }}</td><td>{{ $department->name }}</td><td>{{ $department->code }}</td><td><span class="badge bg-{{ $department->status?'success':'secondary' }}">{{ $department->status?'Active':'Inactive' }}</span></td><td class="text-center"><a class="btn btn-sm btn-outline-primary" href="{{ route('departments.index',['edit'=>$department->id]) }}"><i class="ti ti-edit"></i></a><form class="d-inline" method="POST" action="{{ route('departments.delete',$department) }}" onsubmit="return confirm('Delete this department?')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger"><i class="ti ti-trash"></i></button></form></td></tr>@empty<tr><td colspan="5" class="text-center text-secondary py-4">No departments found.</td></tr>@endforelse</tbody></table></div><div class="card-footer">@include('partials.admin-pagination',['paginator'=>$departments])</div></div>
<div class="modal modal-blur fade" id="departmentModal" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><form method="POST" action="{{ route('departments.save') }}">@csrf<div class="modal-header"><h5 class="modal-title">{{ $editDepartment?'Edit Department':'Create Department' }}</h5><a class="btn-close" href="{{ route('departments.index') }}"></a></div><div class="modal-body"><input type="hidden" name="department_id" value="{{ $editDepartment?->id }}"><div class="department-field"><label class="form-label">Department Name</label><input class="form-control" name="name" value="{{ old('name',$editDepartment?->name) }}" required></div><div class="department-field"><label class="form-label">Code</label><input class="form-control" name="code" value="{{ old('code',$editDepartment?->code) }}" required></div><div class="department-status-row"><select class="d-none" name="status"><option value="1" @selected((string)$departmentStatus==='1')>Active</option><option value="0" @selected((string)$departmentStatus==='0')>Inactive</option></select><button type="button" class="status-toggle {{ $departmentStatus ? 'is-active' : '' }}" id="departmentStatusToggle" aria-pressed="{{ $departmentStatus ? 'true' : 'false' }}"><span class="status-toggle-label">{{ $departmentStatus ? 'ON' : 'OFF' }}</span><span class="status-toggle-knob"></span></button></div></div><div class="modal-footer"><a class="btn me-auto" href="{{ route('departments.index') }}">Cancel</a><button class="btn btn-primary">{{ $editDepartment?'Update':'Create' }}</button></div></form></div></div></div>
<script>
document.addEventListener('DOMContentLoaded',()=>{
    const modal=document.getElementById('departmentModal');
    modal?.querySelectorAll('.department-field').forEach(field=>{const control=field.querySelector('input');const sync=()=>field.classList.toggle('has-value',Boolean(control.value));control.addEventListener('input',sync);sync();});
    const status=modal?.querySelector('select[name="status"]'),toggle=modal?.querySelector('#departmentStatusToggle');
    toggle?.addEventListener('click',()=>{status.value=status.value==='1'?'0':'1';const active=status.value==='1';toggle.classList.toggle('is-active',active);toggle.querySelector('.status-toggle-label').textContent=active?'ON':'OFF';toggle.setAttribute('aria-pressed',active?'true':'false');});
    document.getElementById('btnNewDepartment')?.addEventListener('click',()=>new bootstrap.Modal(modal).show());
    @if($editDepartment)new bootstrap.Modal(modal).show();@endif
});
</script>
@endsection
