@extends('layouts.app')
@section('title', 'Education Levels')
@section('page-header')
<div class="container-fluid"><div class="row g-2 align-items-center"><div class="col"><div class="page-pretitle">Settings</div><h2 class="page-title">Education Levels</h2></div><div class="col-auto"><button class="btn btn-primary" id="newEducationLevel"><i class="ti ti-plus icon"></i> New Education Level</button></div></div></div>
@endsection
@section('content')
<div class="col-12"><div class="card"><div class="card-header"><h3 class="card-title">Education Level Lists</h3></div><div class="card-body border-bottom py-3 d-flex justify-content-between"><div>Show <select id="education-levels-per-page" class="form-control form-control-sm d-inline-block w-auto"><option selected>10</option><option>25</option><option>50</option><option>100</option></select> entries</div><input id="education-levels-search" class="form-control form-control-sm w-auto" placeholder="Search education levels"></div><div class="table-responsive"><table class="table card-table"><thead><tr><th>Level Name</th><th>Short Name</th><th>Order</th><th>Description</th><th>Status</th><th class="text-center">Actions</th></tr></thead><tbody id="educationLevelsTable"></tbody></table></div><div class="card-footer"><div id="education-levels-pagination-container"></div></div></div></div>
<div class="modal modal-blur fade" id="educationLevelModal" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><form id="educationLevelForm" novalidate>@csrf<input type="hidden" id="education_level_id" name="education_level_id"><div class="modal-header"><h5 id="educationLevelModalTitle" class="modal-title">Create Education Level</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="alert alert-danger d-none" data-form-alert></div><div class="row g-3"><div class="col-8"><label class="form-label">Level Name <span class="text-danger">*</span></label><input id="level_name" name="level_name" class="form-control"><div class="invalid-feedback" data-error-for="level_name"></div></div><div class="col-4"><label class="form-label">Short Name <span class="text-danger">*</span></label><input id="level_short_name" name="level_short_name" class="form-control"><div class="invalid-feedback" data-error-for="level_short_name"></div></div><div class="col-4"><label class="form-label">Order</label><input id="level_order" name="level_order" class="form-control"></div><div class="col-8"><label class="form-label">Status</label><select id="status" name="status" class="form-select"><option value="1">Active</option><option value="0">Inactive</option></select></div><div class="col-12"><label class="form-label">Description</label><textarea id="description" name="description" class="form-control"></textarea></div></div></div><div class="modal-footer"><button type="button" class="btn me-auto" data-bs-dismiss="modal">Close</button><button class="btn btn-primary" id="educationLevelSubmit">Create</button></div></form></div></div></div>
@vite('resources/js/educationLevel.js')
@endsection
