@extends('layouts.app')
@section('title', $mode === 'promotion' ? 'Student Promotion' : 'Student Transfer')
@section('page-header')
<div class="container-fluid"><div class="row g-2 align-items-center"><div class="col"><div class="page-pretitle">Students</div><h2 class="page-title">Promotion and Transfer</h2></div><div class="col-auto"><a class="btn" href="{{ route('studentEnrollment.index') }}">Back to Enrollment</a><a class="btn btn-outline-primary ms-2" href="{{ route('studentGraduation.index') }}">Graduation</a><button class="btn btn-primary ms-2" id="newWorkflow"><i class="ti ti-plus icon"></i> New Action</button></div></div></div>
@endsection
@section('content')
<script>document.addEventListener('DOMContentLoaded',()=>{const mode=@json($mode);const label=mode==='promotion'?'Promotion':'Transfer';document.querySelector('.page-title').textContent='Student '+label;document.querySelector('.card-title').textContent=label+' History';const button=document.getElementById('newWorkflow');if(button)button.innerHTML='<i class="ti ti-plus icon"></i> New '+label;});</script>
<style>
    .workflow-section-title { margin-top: .5rem; padding: .65rem .75rem; border: 1px solid var(--tblr-border-color); border-radius: var(--tblr-border-radius); background: var(--tblr-bg-surface-secondary); font-weight: 600; color: var(--tblr-primary); }
</style>
<div class="card"><div class="card-header"><h3 class="card-title">Promotion and Transfer History</h3></div><div class="card-body border-bottom py-3 d-flex justify-content-between"><div>Show <select id="workflow-per-page" class="form-control form-control-sm d-inline-block w-auto"><option selected>10</option><option>25</option><option>50</option><option>100</option></select> entries</div><input id="workflow-search" class="form-control form-control-sm w-auto" placeholder="Search student"></div><div class="table-responsive"><table class="table card-table"><thead><tr><th>Student</th><th>Action</th><th>Academic Year</th><th>Campus</th><th>Grade</th><th>Class</th><th>Group</th><th>Effective Date</th><th>Changed By</th></tr></thead><tbody id="workflowTable"><tr><td colspan="9" class="text-center">Loading...</td></tr></tbody></table></div><div class="card-footer"><div id="workflow-pagination-container"></div></div></div>
<div class="modal modal-blur fade" id="workflowModal" tabindex="-1"><div class="modal-dialog modal-dialog-centered modal-lg"><div class="modal-content"><form id="workflowForm"><div class="modal-header"><h3 class="modal-title">Promotion or Transfer</h3><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="alert alert-danger d-none" id="workflowError"></div><div class="row g-3"><div class="col-12"><label class="form-label">Action *</label><select id="action_type" class="form-select"><option value="promotion">Promotion — Student</option><option value="class_promotion">Promotion — Entire Class</option><option value="transfer">Transfer — Student</option></select></div><div class="col-12 student-action"><label class="form-label">Student Enrollment *</label><select id="enrollment_id" class="form-select"></select></div><div class="row g-3 class-action d-none"><div class="col-md-6"><label class="form-label">Source Campus *</label><select id="from_campus_id" class="form-select"></select></div><div class="col-md-6"><label class="form-label">Source Academic Year *</label><select id="from_academic_year_id" class="form-select"></select></div><div class="col-md-4"><label class="form-label">Source Grade *</label><select id="from_grade_id" class="form-select"></select></div><div class="col-md-4"><label class="form-label">Source Class *</label><select id="from_class_id" class="form-select"></select></div></div><div class="col-md-6 target-year"><label class="form-label">Target Academic Year *</label><select id="to_academic_year_id" class="form-select"></select></div><div class="col-md-6"><label class="form-label">Target Campus</label><select id="to_campus_id" class="form-select"></select></div><div class="col-md-4"><label class="form-label">Target Grade</label><select id="to_grade_id" class="form-select"></select></div><div class="col-md-4"><label class="form-label">Target Class</label><select id="to_class_id" class="form-select"></select></div><div class="col-md-4"><label class="form-label">Target Group</label><select id="to_session_id" class="form-select"></select></div><div class="col-md-6"><label class="form-label">Effective Date *</label><input type="date" id="effective_on" class="form-control" required></div><div class="col-md-6"><label class="form-label">Reason</label><input id="reason" class="form-control"></div><div class="col-12"><label class="form-label">Notes</label><textarea id="notes" class="form-control" rows="3"></textarea></div></div></div><div class="modal-footer"><button type="button" class="btn me-auto" data-bs-dismiss="modal">Cancel</button><button class="btn btn-primary">Save Action</button></div></form></div></div></div>
<script>
(() => {
    window.addEventListener('load', () => {
    const csrf = document.querySelector('meta[name="csrf-token"]')?.content || '';
    const modal = bootstrap.Modal.getOrCreateInstance(document.getElementById('workflowModal'));
    const form = document.getElementById('workflowForm');
    const field = (id) => document.getElementById(id);
    let options = {};
    const searchable = {};
    const addWorkflowSections = () => { const student = document.querySelector('.student-action'); const source = document.querySelector('.class-action'); const target = document.querySelector('.target-year'); if (student && !student.previousElementSibling?.classList.contains('workflow-section-title')) student.insertAdjacentHTML('beforebegin', '<div class="col-12 workflow-section-title">Current Enrollment</div>'); if (source && !source.querySelector('.workflow-section-title')) source.insertAdjacentHTML('afterbegin', '<div class="col-12 workflow-section-title">Current Class</div>'); if (target && !document.querySelector('.target-section-title')) target.insertAdjacentHTML('beforebegin', '<div class="col-12 workflow-section-title target-section-title">Promote / Transfer To</div>'); };
    const esc = (value = '') => String(value).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');
    const renderSearchable = (id) => { const item = searchable[id]; if (!item) return; const term = item.search.value.trim().toLowerCase(); const options = Array.from(item.select.options).slice(1).filter((option) => `${option.textContent} ${option.dataset.info || ''}`.toLowerCase().includes(term)); item.results.innerHTML = options.length ? options.map((option) => `<button type="button" class="location-combobox-option" data-value="${option.value}"><span class="d-block">${esc(option.textContent)}</span>${option.dataset.info ? `<small class="text-secondary d-block">${esc(option.dataset.info)}</small>` : ''}</button>`).join('') : '<div class="text-secondary px-2 py-2">No results found</div>'; item.results.querySelectorAll('[data-value]').forEach((button) => button.onclick = () => { item.select.value = button.dataset.value; item.select.dispatchEvent(new Event('change', { bubbles: true })); item.selected.textContent = button.querySelector('span')?.textContent || button.textContent; if (item.info) item.info.textContent = item.select.options[item.select.selectedIndex]?.dataset.info || ''; item.menu.classList.add('d-none'); }); };
    const makeSearchable = (id) => { if (searchable[id]) return; const select = field(id); if (!select) return; select.classList.add('d-none'); const wrapper = document.createElement('div'); wrapper.className = 'location-combobox'; wrapper.innerHTML = `<button type="button" class="location-combobox-toggle"><span class="location-combobox-selected">Select</span><i class="ti ti-chevron-down"></i></button><div class="location-combobox-menu d-none"><input type="search" class="form-control location-combobox-search" placeholder="${id === 'enrollment_id' ? 'Search by Student ID or name' : 'Search'}"><div class="location-combobox-results"></div></div>${id === 'enrollment_id' ? '<div class="workflow-current-info text-secondary small mt-2"></div>' : ''}`; select.after(wrapper); const item = searchable[id] = { select, selected: wrapper.querySelector('.location-combobox-selected'), menu: wrapper.querySelector('.location-combobox-menu'), search: wrapper.querySelector('.location-combobox-search'), results: wrapper.querySelector('.location-combobox-results'), info: wrapper.querySelector('.workflow-current-info') }; wrapper.querySelector('.location-combobox-toggle').onclick = () => { Object.values(searchable).forEach((other) => { if (other !== item) other.menu.classList.add('d-none'); }); item.menu.classList.toggle('d-none'); item.search.value = ''; renderSearchable(id); item.search.focus(); }; item.search.oninput = () => renderSearchable(id); renderSearchable(id); };
    const refreshSearchables = () => ['enrollment_id','from_campus_id','from_academic_year_id','from_grade_id','from_class_id','to_academic_year_id','to_campus_id','to_grade_id','to_class_id','to_session_id'].forEach(makeSearchable);
    const refreshSearchableValues = () => Object.keys(searchable).forEach((id) => { const item = searchable[id]; const selected = item.select.options[item.select.selectedIndex]; item.selected.textContent = selected?.value ? selected.textContent : `Select`; if (item.info) item.info.textContent = selected?.dataset.info || ''; renderSearchable(id); });
    if (!field('action_type').querySelector('option[value="class_transfer"]')) field('action_type').insertAdjacentHTML('beforeend', '<option value="class_transfer">Transfer — Entire Class</option>');
    if (!field('action_type').querySelector('option[value="selected_promotion"]')) field('action_type').insertAdjacentHTML('beforeend', '<option value="selected_promotion">Promotion - Selected Students</option>');
    if (!field('action_type').querySelector('option[value="selected_transfer"]')) field('action_type').insertAdjacentHTML('beforeend', '<option value="selected_transfer">Transfer - Selected Students</option>');
    const fill = (id, items, value, label) => { field(id).innerHTML = `<option value="">Select ${label}</option>` + items.map((item) => `<option value="${item.id}">${esc(item[value])}</option>`).join(''); refreshSearchableValues(); };
    const loadOptions = async () => { options = await (await fetch('/student-enrollment-workflows/options')).json(); fill('to_academic_year_id', options.academicYears || [], 'academic_year', 'Academic Year'); fill('from_academic_year_id', options.academicYears || [], 'academic_year', 'Academic Year'); fill('to_campus_id', options.campuses || [], 'campus_name_en', 'Campus'); fill('from_campus_id', options.campuses || [], 'campus_name_en', 'Campus'); fill('to_grade_id', options.grades || [], 'grade', 'Grade'); fill('from_grade_id', options.grades || [], 'grade', 'Grade'); fill('to_class_id', options.classes || [], 'class_name', 'Class'); fill('from_class_id', options.classes || [], 'class_name', 'Class'); fill('to_session_id', options.groups || [], 'session_short_name', 'Group'); field('enrollment_id').innerHTML = `<option value="">Select Student</option>` + (options.enrollments || []).map((item) => { const name = `${item.student?.student_id || item.student?.student_no || ''} - ${item.student?.first_name_en || ''} ${item.student?.last_name_en || ''}`; const info = `${item.academic_year?.academic_year || '-'} | ${item.campus?.campus_name_en || '-'} | ${item.grade?.grade || '-'} | ${item.school_class?.class_name || '-'} | Group ${item.session?.session_short_name || '-'}`; return `<option value="${item.id}" data-info="${esc(info)}">${esc(name)}</option>`; }).join(''); refreshSearchables(); refreshSearchableValues(); };
    const renderPagination = (result, pageSize) => { const container = document.getElementById('workflow-pagination-container'); const pages = result.last_page <= 5 ? Array.from({ length: result.last_page }, (_, i) => i + 1) : [1, 'ellipsis', result.current_page, 'ellipsis', result.last_page]; container.innerHTML = `<div class="premium-pagination"><ul class="pagination premium-pagination-list m-0"><li class="page-item ${result.current_page === 1 ? 'disabled' : ''}"><a class="page-link" href="#" data-page="${result.current_page - 1}"><i class="ti ti-chevron-left icon icon-1"></i></a></li>${pages.map((page) => page === 'ellipsis' ? '<li class="premium-pagination-ellipsis">…</li>' : `<li class="page-item ${page === result.current_page ? 'active' : ''}"><a class="page-link" href="#" data-page="${page}">${page}</a></li>`).join('')}<li class="page-item ${result.current_page === result.last_page ? 'disabled' : ''}"><a class="page-link" href="#" data-page="${result.current_page + 1}"><i class="ti ti-chevron-right icon icon-1"></i></a></li></ul><p class="premium-pagination-info m-0">Showing <strong>${result.from ?? 0} to ${result.to ?? 0}</strong> of <strong>${result.total} entries</strong></p><div class="premium-pagination-controls"><label class="premium-pagination-select"><select class="form-select form-select-sm">${[10,25,50,100].map((value) => `<option value="${value}" ${String(value) === String(pageSize) ? 'selected' : ''}>${value} / page</option>`).join('')}</select></label></div></div>`; container.querySelectorAll('.page-link').forEach((link) => link.onclick = (event) => { event.preventDefault(); const page = Number(link.dataset.page); if (page >= 1 && page <= result.last_page && page !== result.current_page) render(page, pageSize); }); container.querySelector('select')?.addEventListener('change', (event) => { field('workflow-per-page').value = event.target.value; render(1, Number(event.target.value)); }); };
    const selectedStudentsPanel = document.createElement('div'); selectedStudentsPanel.className = 'col-12 selected-students-action d-none'; selectedStudentsPanel.innerHTML = '<div class="workflow-section-title">Select Students to Promote</div><div class="d-flex justify-content-between align-items-center mt-2 mb-2"><span class="text-secondary small">Only selected students will be promoted. Unselected students remain in the current class.</span><button type="button" class="btn btn-sm btn-outline-primary" id="select-all-class-students">Select All</button></div><div id="selected-students-list" class="border rounded p-2" style="max-height:220px;overflow:auto"></div>'; document.querySelector('.class-action')?.after(selectedStudentsPanel);
    const renderSelectedStudents = () => { const values = ['from_campus_id','from_academic_year_id','from_grade_id','from_class_id'].map((id) => field(id).value); const targetYear = field('to_academic_year_id').value; const targetStudentIds = new Set((options.enrollments || []).filter((item) => targetYear && String(item.academic_year_id) === String(targetYear)).map((item) => String(item.student_id))); const matching = (options.enrollments || []).filter((item) => [item.campus_id, item.academic_year_id, item.grade_id, item.class_id].every((value, index) => String(value) === String(values[index])) && item.status && item.enrollment_status === 'active' && !targetStudentIds.has(String(item.student_id))); const list = document.getElementById('selected-students-list'); if (!list) return; list.innerHTML = matching.length ? matching.map((item) => { const name = `${item.student?.student_id || item.student?.student_no || ''} - ${item.student?.first_name_en || ''} ${item.student?.last_name_en || ''}`; return `<label class="form-check mb-1"><input class="form-check-input selected-class-student" type="checkbox" value="${item.id}"><span class="form-check-label">${esc(name)}</span></label>`; }).join('') : '<div class="text-secondary small">No students are pending promotion in the selected class.</div>'; };
    const render = async (page = 1, pageSize = Number(field('workflow-per-page').value)) => { const term = encodeURIComponent(field('workflow-search').value || ''); const result = await (await fetch(`/student-enrollment-workflows/fetch?page=${page}&perPage=${pageSize}&search=${term}`)).json(); const rows = result.data || []; document.getElementById('workflowTable').innerHTML = rows.length ? rows.map((item) => `<tr><td>${esc(`${item.student?.student_no || ''} - ${item.student?.first_name_en || ''} ${item.student?.last_name_en || ''}`)}</td><td><span class="badge bg-${item.action_type === 'promotion' ? 'green' : 'blue'}-lt">${esc(item.action_type)}</span></td><td>${esc(item.to_academic_year?.academic_year || '-')}</td><td>${esc(item.to_campus?.campus_name_en || '-')}</td><td>${esc(item.to_grade?.grade || '-')}</td><td>${esc(item.to_class?.class_name || '-')}</td><td>${esc(item.to_session?.session_short_name || '-')}</td><td>${esc(item.effective_on || '-')}</td><td>${esc(item.changed_by?.name || 'System')}</td></tr>`).join('') : '<tr><td colspan="9" class="text-center">No workflow actions found.</td></tr>'; renderPagination(result, pageSize); };
    field('action_type').onchange = () => { const action = field('action_type').value; const classAction = ['class_promotion', 'selected_promotion', 'selected_transfer', 'class_transfer'].includes(action); const selectedAction = ['selected_promotion', 'selected_transfer'].includes(action); document.querySelector('.class-action').classList.toggle('d-none', !classAction); document.querySelector('.student-action').classList.toggle('d-none', classAction); document.querySelector('.target-year').classList.toggle('d-none', ['transfer', 'selected_transfer', 'class_transfer'].includes(action)); selectedStudentsPanel.classList.toggle('d-none', !selectedAction); selectedStudentsPanel.querySelector('.workflow-section-title').textContent = action === 'selected_transfer' ? 'Select Students to Transfer' : 'Select Students to Promote'; selectedStudentsPanel.querySelector('.text-secondary').textContent = action === 'selected_transfer' ? 'Only selected students will be transferred. Unselected students remain in the current class.' : 'Only selected students will be promoted. Unselected students remain in the current class.'; if (selectedAction) renderSelectedStudents(); };
    ['from_campus_id','from_academic_year_id','from_grade_id','from_class_id','to_academic_year_id'].forEach((id) => field(id).addEventListener('change', renderSelectedStudents));
    document.addEventListener('click', (event) => { if (event.target.id === 'select-all-class-students') document.querySelectorAll('.selected-class-student').forEach((checkbox) => { checkbox.checked = true; }); });
    document.getElementById('newWorkflow').onclick = async () => { await loadOptions(); form.reset(); field('effective_on').value = new Date().toISOString().slice(0,10); field('action_type').dispatchEvent(new Event('change')); field('workflowError').classList.add('d-none'); modal.show(); };
    document.getElementById('workflow-search').oninput = () => render();
    form.onsubmit = async (event) => { event.preventDefault(); const action = field('action_type').value; const classAction = ['class_promotion', 'selected_promotion', 'selected_transfer', 'class_transfer'].includes(action); const ids = classAction ? ['from_campus_id','from_academic_year_id','from_grade_id','from_class_id','to_campus_id','to_academic_year_id','to_grade_id','to_class_id','to_session_id','effective_on','reason','notes'] : ['enrollment_id','to_academic_year_id','to_campus_id','to_grade_id','to_class_id','to_session_id','effective_on','reason','notes']; const payload = Object.fromEntries(ids.map((id) => [id, field(id).value])); if (['selected_promotion', 'selected_transfer'].includes(action)) payload.enrollment_ids = Array.from(document.querySelectorAll('.selected-class-student:checked')).map((checkbox) => Number(checkbox.value)); const endpoint = action === 'class_promotion' ? 'class-promote' : action === 'selected_promotion' ? 'selected-promote' : action === 'selected_transfer' ? 'selected-transfer' : action === 'class_transfer' ? 'class-transfer' : action === 'promotion' ? 'promote' : 'transfer'; const response = await fetch(`/student-enrollment-workflows/${endpoint}`, { method: 'POST', headers: { Accept: 'application/json', 'Content-Type': 'application/json', 'X-CSRF-TOKEN': csrf }, body: JSON.stringify(payload) }); const result = await response.json(); if (!response.ok) { field('workflowError').textContent = result.message || 'Unable to save workflow action.'; field('workflowError').classList.remove('d-none'); return; } modal.hide(); await render(); };
    addWorkflowSections();
    render();
    });
})();
</script>
<script>document.addEventListener('DOMContentLoaded',()=>{window.addEventListener('load',()=>setTimeout(()=>{const mode=@json($mode),allowed=mode==='promotion'?['promotion','class_promotion','selected_promotion']:['transfer','class_transfer','selected_transfer'];const select=document.getElementById('action_type');if(select){Array.from(select.options).forEach(option=>{option.hidden=!allowed.includes(option.value);});select.value=allowed[0];}const title=document.querySelector('#workflowModal .modal-title');if(title)title.textContent=mode==='promotion'?'Student Promotion':'Student Transfer';},0);});});</script>
@endsection
