@extends('layouts.app')

@section('title', 'Withdraw Student')
@section('page-header')
<div class="container-fluid"><div class="row g-2 align-items-center"><div class="col"><div class="page-pretitle">Students</div><h2 class="page-title">Student Withdrawal</h2></div><div class="col-auto"><button type="button" class="btn btn-primary" id="newWithdrawal" data-bs-toggle="modal" data-bs-target="#withdrawalModal"><i class="ti ti-user-minus me-1"></i> New Withdrawal</button></div></div></div>
@endsection

@section('content')
<style>.withdrawal-filter-fields input[id="withdrawal-year-search"],.withdrawal-filter-fields input[id="withdrawal-campus-search"],.withdrawal-filter-fields input[id="withdrawal-grade-class-search"],.withdrawal-filter-fields>.col-md-6>.input-icon,.student-withdrawal-field>#withdrawal-student-search,.student-withdrawal-field>.input-icon{display:none!important}#withdrawalModal .modal-dialog{width:calc(100% - 2rem);max-width:1100px}@media (min-width:768px){#withdrawalForm .withdrawal-filter-fields>.col-md-6{width:33.333333%;flex:0 0 auto}#withdrawalForm .student-withdrawal-field{width:66.666667%;flex:0 0 auto}#withdrawalForm .withdrawal-date-column{width:33.333333%;flex:0 0 auto}#withdrawalForm .withdrawal-reason-panel>.row.g-2:first-of-type>.col-md-6{width:33.333333%;flex:0 0 auto}}</style>
<div class="card"><div class="card-header"><h3 class="card-title">Withdrawal History</h3></div><div class="card-body border-bottom py-3 d-flex justify-content-between"><div>Show <select id="withdrawal-per-page" class="form-control form-control-sm d-inline-block w-auto"><option selected>10</option><option>25</option><option>50</option></select> entries</div><input id="withdrawal-search" class="form-control form-control-sm w-auto" placeholder="Search withdrawal history"></div><div class="table-responsive"><table class="table card-table"><thead><tr><th>Student</th><th>Academic Year</th><th>Campus</th><th>Grade</th><th>Class</th><th>Withdrawal Date</th><th>Reason</th><th>Withdrawn By</th><th>Form</th></tr></thead><tbody id="withdrawal-table"><tr><td colspan="9" class="text-center">Loading...</td></tr></tbody></table></div><div class="card-footer"><div id="withdrawal-pagination"></div></div></div>
<div class="modal modal-blur fade" id="withdrawalModal" tabindex="-1"><div class="modal-dialog modal-dialog-centered modal-lg"><div class="modal-content"><form id="withdrawalForm"><div class="modal-header"><h3 class="modal-title">Withdraw Student</h3><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="alert alert-danger d-none" id="withdrawal-error"></div><div class="row g-3"><div class="col-12"><label class="form-label">Withdrawal Type *</label><select id="withdrawal-type" class="form-select"><option value="student">Withdraw Student</option><option value="selected">Withdraw Selected Students</option><option value="class">Withdraw Entire Class</option></select></div><div class="row g-3 withdrawal-filter-fields"><div class="col-md-6"><label class="form-label">Academic Year *</label><input id="withdrawal-year-search" class="form-control form-control-sm mb-1" placeholder="Search academic year"><select id="withdrawal-year" class="form-select"></select></div><div class="col-md-6"><label class="form-label">Campus *</label><input id="withdrawal-campus-search" class="form-control form-control-sm mb-1" placeholder="Search campus"><select id="withdrawal-campus" class="form-select"></select></div><div class="col-md-6"><label class="form-label">Grade + Class *</label><input id="withdrawal-grade-class-search" class="form-control form-control-sm mb-1" placeholder="Search Grade 1A"><select id="withdrawal-grade-class" class="form-select"></select><select id="withdrawal-grade" class="d-none"></select><select id="withdrawal-class" class="d-none"></select></div></div><div class="col-12 student-withdrawal-field"><label class="form-label">Student Name *</label><input id="withdrawal-student-search" class="form-control mb-2" placeholder="Search Student ID or name"><select id="withdrawal-enrollment-id" class="form-select"></select></div><div class="col-12 selected-withdrawal-list d-none"><label class="form-label">Select Students</label><div id="withdrawal-students" class="border rounded p-2" style="max-height:220px;overflow:auto"></div></div><div class="col-md-6"><label class="form-label">Withdrawal Date *</label><input type="date" id="withdrawal-date" class="form-control" required></div><div class="col-md-6"><label class="form-label">Reason *</label><input id="withdrawal-reason" class="form-control" required></div><div class="col-12"><label class="form-label">Notes</label><textarea id="withdrawal-notes" class="form-control" rows="3"></textarea></div></div></div><div class="modal-footer"><button type="button" class="btn me-auto" data-bs-dismiss="modal">Cancel</button><button class="btn btn-primary">Confirm Withdrawal</button></div></form></div></div></div>
@endsection

@push('scripts')
<script>
document.addEventListener('DOMContentLoaded', function () {
    const modal=bootstrap.Modal.getOrCreateInstance(document.getElementById('withdrawalModal')), form=document.getElementById('withdrawalForm'), field=id=>document.getElementById(id), esc=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[ch])); let options={};
    const reasonPanel=document.createElement('div');reasonPanel.className='withdrawal-reason-panel mb-3';reasonPanel.innerHTML='<label class="form-label">Reason for Withdrawal * <small class="text-secondary">(select all that apply)</small></label><div class="row g-2">'+(@json(\App\Http\Controllers\StudentWithdrawalController::REASONS)).map(reason=>'<div class="col-md-6"><label class="form-check"><input class="form-check-input withdrawal-reason-check" type="checkbox" value="'+reason.key+'" data-en="'+esc(reason.en)+'" data-kh="'+esc(reason.kh)+'"><span class="form-check-label"><span class="d-block school-profile-khmer">'+esc(reason.kh)+'</span>'+esc(reason.en)+'</span></label></div>').join('')+'<div class="col-md-6"><label class="form-check"><input class="form-check-input" type="checkbox" id="withdrawal-other-check"><span class="form-check-label">Other</span></label></div></div><div class="row g-2 mt-1 d-none" id="withdrawal-other-fields"><div class="col-md-6"><input id="withdrawal-other-en" class="form-control" placeholder="Other reason (English)"></div><div class="col-md-6"><input id="withdrawal-other-kh" class="form-control school-profile-khmer" placeholder="មូលហេតុផ្សេងទៀត (ខ្មែរ)"></div></div><div class="row g-2 mt-2"><div class="col-md-6"><label class="form-label">Reason (English)</label><input id="withdrawal-reason-en" class="form-control" readonly></div><div class="col-md-6"><label class="form-label school-profile-khmer">មូលហេតុ (ខ្មែរ)</label><input id="withdrawal-reason-kh" class="form-control school-profile-khmer" readonly></div></div>';document.querySelector('#withdrawalForm .modal-body')?.prepend(reasonPanel);field('withdrawal-reason')?.classList.add('d-none');
    const syncReasons=()=>{const selected=Array.from(document.querySelectorAll('.withdrawal-reason-check:checked'));const otherEn=field('withdrawal-other-en')?.value.trim()||'',otherKh=field('withdrawal-other-kh')?.value.trim()||'';const en=selected.map(item=>item.dataset.en).concat(otherEn?[otherEn]:[]).filter(Boolean),kh=selected.map(item=>item.dataset.kh).concat(otherKh?[otherKh]:[]).filter(Boolean);field('withdrawal-reason-en').value=en.join('; ');field('withdrawal-reason-kh').value=kh.join('; ');if(field('withdrawal-reason'))field('withdrawal-reason').value=en.join('; ');};document.addEventListener('change',event=>{if(event.target.matches('.withdrawal-reason-check,#withdrawal-other-check')){field('withdrawal-other-fields')?.classList.toggle('d-none',!field('withdrawal-other-check')?.checked);syncReasons();}});document.addEventListener('input',event=>{if(event.target.matches('#withdrawal-other-en,#withdrawal-other-kh'))syncReasons();});
    ['withdrawal-year-search','withdrawal-campus-search','withdrawal-grade-class-search','withdrawal-student-search'].forEach(id=>{const input=field(id);if(input){input.dataset.searchNormalized='true';input.classList.add('d-none');}});
    const fill=(id,items,label,empty)=>{field(id).innerHTML='<option value="">'+empty+'</option>'+items.map(item=>'<option value="'+item.id+'">'+esc(item[label])+'</option>').join('');};
    const filterSelect=(selectId,searchId)=>{const select=field(selectId),term=(field(searchId)?.value||'').toLowerCase();Array.from(select.options).forEach((option,index)=>{option.hidden=index>0&&!option.text.toLowerCase().includes(term);});};
    const setupSearchableSelect=(id,label)=>{const select=field(id);if(!select||field(id+'-combobox'))return;select.classList.add('d-none');select.insertAdjacentHTML('afterend','<div id="'+id+'-combobox" class="location-combobox withdrawal-search-combobox"><button type="button" id="'+id+'-toggle" class="location-combobox-toggle"><span id="'+id+'-selected" class="location-combobox-selected">Select '+label+'</span><i class="ti ti-chevron-down"></i></button><div id="'+id+'-menu" class="location-combobox-menu d-none"><input id="'+id+'-menu-search" type="search" class="form-control location-combobox-search" placeholder="Search '+label+'"><div id="'+id+'-results" class="location-combobox-results"></div></div></div>');const menu=field(id+'-menu'),searchInput=field(id+'-menu-search'),results=field(id+'-results'),selected=field(id+'-selected');const sync=()=>{selected.textContent=select.value?select.selectedOptions[0]?.textContent||'':'';};const render=()=>{const term=searchInput.value.toLowerCase();const opts=Array.from(select.options).slice(1).filter(option=>!term||option.textContent.toLowerCase().includes(term));results.innerHTML=opts.length?opts.map(option=>'<button type="button" class="location-combobox-option" data-withdrawal-select="'+id+'" data-value="'+option.value+'">'+esc(option.textContent)+'</button>').join(''):'<div class="text-secondary px-2 py-2">No options found</div>';};field(id+'-toggle').onclick=()=>{document.querySelectorAll('.withdrawal-search-combobox .location-combobox-menu').forEach(other=>{if(other!==menu)other.classList.add('d-none');});menu.classList.toggle('d-none');if(!menu.classList.contains('d-none')){searchInput.value='';render();searchInput.focus();}};searchInput.oninput=render;select.addEventListener('change',()=>{sync();render();});results.onclick=event=>{const option=event.target.closest('[data-withdrawal-select]');if(!option)return;select.value=option.dataset.value;select.dispatchEvent(new Event('change',{bubbles:true}));menu.classList.add('d-none');};sync();render();};
    document.addEventListener('click',event=>{if(!event.target.closest('.withdrawal-search-combobox'))document.querySelectorAll('.withdrawal-search-combobox .location-combobox-menu').forEach(menu=>menu.classList.add('d-none'));});
    const studentName=item=>`${item.student?.student_id||item.student?.student_no||''} - ${item.student?.first_name_en||''} ${item.student?.last_name_en||''}`;
    const studentQuery=()=>{const params=new URLSearchParams({campus_id:field('withdrawal-campus').value,academic_year_id:field('withdrawal-year').value,grade_id:field('withdrawal-grade').value,class_id:field('withdrawal-class').value,search:field('withdrawal-student-search').value});return '{{ route('student-withdrawals.students') }}?'+params.toString();};
    const updateGradeClasses=(items)=>{field('withdrawal-grade-class').innerHTML='<option value="">Select Grade + Class</option>'+(items||[]).map(item=>'<option value="'+item.grade_id+'|'+item.class_id+'">'+esc(gradeCode(item.grade)+item.class_name)+'</option>').join('');field('withdrawal-grade').value='';field('withdrawal-class').value='';field('withdrawal-grade-class').dispatchEvent(new Event('change'));};
    const refreshDependentOptions=async()=>{if(!field('withdrawal-year').value){fill('withdrawal-campus',[],'campus_name_en','Select Campus');updateGradeClasses([]);clearStudentResults();return;}const params=new URLSearchParams({academic_year_id:field('withdrawal-year').value,campus_id:field('withdrawal-campus').value});const result=await fetch('{{ route('student-withdrawals.options') }}?'+params.toString()).then(response=>response.json());const currentCampus=field('withdrawal-campus').value;fill('withdrawal-campus',result.campuses||[],'campus_name_en','Select Campus');if((result.campuses||[]).some(item=>String(item.id)===String(currentCampus)))field('withdrawal-campus').value=currentCampus;else field('withdrawal-campus').value='';updateGradeClasses(field('withdrawal-campus').value?result.gradeClasses||[]:[]);renderStudentSelect();};
    const hasAllStudentFilters=()=>Boolean(field('withdrawal-year').value&&field('withdrawal-campus').value&&field('withdrawal-grade').value&&field('withdrawal-class').value);
    const clearStudentResults=()=>{field('withdrawal-enrollment-id').innerHTML='<option value="">Select Student</option>';field('withdrawal-enrollment-id').dispatchEvent(new Event('change'));field('withdrawal-students').innerHTML='<div class="text-secondary small">Select Academic Year, Campus, and Grade + Class first.</div>';};
    const renderStudents=async()=>{if(!hasAllStudentFilters()){clearStudentResults();return;}const rows=(await fetch(studentQuery()).then(response=>response.json())).enrollments||[];const list=field('withdrawal-students');list.innerHTML=rows.length?rows.map(item=>'<label class="form-check mb-1"><input class="form-check-input withdrawal-student" type="checkbox" value="'+item.id+'"><span class="form-check-label">'+esc(studentName(item))+'</span></label>').join(''):'<div class="text-secondary small">No active students found.</div>';};
    const renderStudentSelect=async()=>{if(!hasAllStudentFilters()){clearStudentResults();return;}const result=await fetch(studentQuery()).then(response=>response.json());const enrollments=result.enrollments||[];field('withdrawal-enrollment-id').innerHTML='<option value="">Select Student</option>'+enrollments.map(item=>'<option value="'+item.id+'">'+esc(studentName(item))+'</option>').join('');field('withdrawal-enrollment-id').dispatchEvent(new Event('change'));};
    const updateType=()=>{const type=field('withdrawal-type').value, bulk=type!=='student';document.querySelector('.student-withdrawal-field').classList.toggle('d-none',bulk);document.querySelector('.selected-withdrawal-list').classList.toggle('d-none',type!=='selected');if(type!=='student')renderStudents();};
    const gradeCode=grade=>{const value=String(grade||'').trim();if(value.toLowerCase()==='nursery')return 'N';return value.replace(/^Grade\s+/i,'');};
    const loadOptions=async()=>{options=await fetch('{{ route('student-withdrawals.options') }}').then(r=>r.json());fill('withdrawal-campus',[],'campus_name_en','Select Campus');fill('withdrawal-year',options.academicYears||[],'academic_year','Select Academic Year');fill('withdrawal-grade',options.grades||[],'grade','Select Grade');fill('withdrawal-class',options.classes||[],'class_name','Select Class');field('withdrawal-grade-class').innerHTML='<option value="">Select Grade + Class</option>';setupSearchableSelect('withdrawal-year','Academic Year');setupSearchableSelect('withdrawal-campus','Campus');setupSearchableSelect('withdrawal-grade-class','Grade + Class');setupSearchableSelect('withdrawal-enrollment-id','Student Name');['withdrawal-year','withdrawal-campus','withdrawal-grade-class','withdrawal-enrollment-id'].forEach(id=>field(id+'-toggle')?.insertAdjacentHTML('afterbegin','<i class="ti ti-search me-1"></i>'));field('withdrawal-grade-class').onchange=()=>{const [gradeId,classId]=field('withdrawal-grade-class').value.split('|');field('withdrawal-grade').value=gradeId||'';field('withdrawal-class').value=classId||'';renderStudentSelect();renderStudents();};clearStudentResults();};
    field('withdrawal-type').onchange=updateType;field('withdrawal-year').onchange=refreshDependentOptions;field('withdrawal-campus').onchange=refreshDependentOptions;field('withdrawal-student-search').classList.add('d-none');field('withdrawal-student-search').oninput=renderStudentSelect;[['withdrawal-year','withdrawal-year-search'],['withdrawal-campus','withdrawal-campus-search'],['withdrawal-grade-class','withdrawal-grade-class-search']].forEach(([selectId,searchId])=>field(searchId).oninput=()=>filterSelect(selectId,searchId));
    document.getElementById('newWithdrawal').onclick=async()=>{form.reset();field('withdrawal-date').value=new Date().toISOString().slice(0,10);field('withdrawal-error').classList.add('d-none');modal.show();updateType();await loadOptions();updateType();};
    form.onsubmit=async event=>{event.preventDefault();const type=field('withdrawal-type').value;const common={withdrawal_date:field('withdrawal-date').value,reason:field('withdrawal-reason').value,notes:field('withdrawal-notes').value};let endpoint,payload;if(type==='student'){endpoint='withdraw';payload={...common,enrollment_id:field('withdrawal-enrollment-id').value};}else{payload={...common,from_campus_id:field('withdrawal-campus').value,from_academic_year_id:field('withdrawal-year').value,from_grade_id:field('withdrawal-grade').value,from_class_id:field('withdrawal-class').value};if(type==='selected'){endpoint='withdraw-selected';payload.enrollment_ids=Array.from(document.querySelectorAll('.withdrawal-student:checked')).map(input=>Number(input.value));}else endpoint='withdraw-class';}const response=await fetch('{{ url('/student-withdrawals') }}/'+endpoint,{method:'POST',headers:{Accept:'application/json','Content-Type':'application/json','X-CSRF-TOKEN':'{{ csrf_token() }}'},body:JSON.stringify(payload)});const result=await response.json();if(!response.ok){field('withdrawal-error').textContent=result.message||Object.values(result.errors||{})[0]?.[0]||'Unable to withdraw student.';field('withdrawal-error').classList.remove('d-none');return;}modal.hide();loadHistory();};
    const renderHistoryPagination=result=>{const pagination=field('withdrawal-pagination');if(!pagination)return;const current=result.current_page||1,last=result.last_page||1;if(last<=1){pagination.innerHTML='';return;}pagination.innerHTML='<div class="d-flex justify-content-end gap-1 flex-wrap">'+Array.from({length:last},(_,index)=>index+1).map(page=>'<button type="button" class="btn btn-sm '+(page===current?'btn-primary':'btn-outline-secondary')+' withdrawal-page" data-page="'+page+'">'+page+'</button>').join('')+'</div>';pagination.querySelectorAll('.withdrawal-page').forEach(button=>button.onclick=()=>loadHistory(Number(button.dataset.page)));};
    const loadHistory=async(page=1)=>{const result=await fetch('{{ route('student-withdrawals.fetch') }}?page='+page+'&perPage='+field('withdrawal-per-page').value+'&search='+encodeURIComponent(field('withdrawal-search').value)).then(r=>r.json());field('withdrawal-table').innerHTML=result.data?.length?result.data.map(item=>'<tr><td>'+esc(studentName(item))+'</td><td>'+esc(item.academic_year?.academic_year||'-')+'</td><td>'+esc(item.campus?.campus_name_en||'-')+'</td><td>'+esc(item.grade?.grade||'-')+'</td><td>'+esc(item.school_class?.class_name||'-')+'</td><td>'+esc(item.effective_on||'-')+'</td><td>'+esc(item.reason||'-')+'</td><td>'+esc(item.changed_by?.name||'System')+'</td></tr>').join(''):'<tr><td colspan="8" class="text-center">No withdrawal history found.</td></tr>';renderHistoryPagination(result);};
    field('withdrawal-per-page').onchange=()=>loadHistory();let searchTimer;field('withdrawal-search').oninput=()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>loadHistory(),300);};loadHistory();
});
</script>
<script>
document.addEventListener('DOMContentLoaded', function () {
    const form = document.getElementById('withdrawalForm');
    if (!form) return;
    const field = id => document.getElementById(id);
    const reasonPanel = document.querySelector('.withdrawal-reason-panel');
    const reasonHeading = reasonPanel?.querySelector('.form-label');
    if (reasonHeading) {
        reasonHeading.outerHTML = '<h5 class="mb-3">REASONS FOR WITHDRAWAL: <small class="text-secondary fw-normal">(Select all that apply)</small></h5>';
    }
    const legacyReason = document.getElementById('withdrawal-reason');
    const legacyReasonColumn = legacyReason?.closest('.col-md-6');
    if (reasonPanel && legacyReasonColumn) {
        legacyReasonColumn.classList.add('d-none');
        legacyReasonColumn.before(reasonPanel);
    }
    document.getElementById('withdrawal-date')?.closest('.col-md-6')?.classList.add('withdrawal-date-column');
    const escapeHtml = value => String(value ?? '').replace(/[&<>"']/g, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[character]));
    const reinforceSearchable = (id, label) => {
        const select = document.getElementById(id);
        if (!select) return;
        let combo = document.getElementById(id + '-combobox');
        if (!combo) {
            select.classList.add('d-none');
            select.insertAdjacentHTML('afterend', '<div id="' + id + '-combobox" class="location-combobox withdrawal-search-combobox"><button type="button" id="' + id + '-toggle" class="location-combobox-toggle"><span id="' + id + '-selected" class="location-combobox-selected">Select ' + label + '</span><i class="ti ti-chevron-down"></i></button><div id="' + id + '-menu" class="location-combobox-menu d-none"><input id="' + id + '-menu-search" type="search" class="form-control location-combobox-search" placeholder="Search ' + label + '"><div id="' + id + '-results" class="location-combobox-results"></div></div></div>');
            combo = document.getElementById(id + '-combobox');
        }
        const search = document.getElementById(id + '-menu-search');
        const results = document.getElementById(id + '-results');
        const selectedDisplay = document.getElementById(id + '-selected');
        if (selectedDisplay && !select.value) selectedDisplay.textContent = '';
        const render = () => {
            const term = (search?.value || '').toLowerCase().trim();
            const items = Array.from(select.options).slice(1).filter(option => !term || option.textContent.toLowerCase().includes(term));
            if (results) results.innerHTML = items.length ? items.map(option => '<button type="button" class="location-combobox-option" data-withdrawal-select="' + id + '" data-value="' + escapeHtml(option.value) + '">' + escapeHtml(option.textContent) + '</button>').join('') : '<div class="text-secondary px-2 py-2">No options found</div>';
        };
        if (search) search.oninput = render;
        document.getElementById(id + '-toggle')?.addEventListener('click', () => { document.querySelectorAll('.withdrawal-search-combobox .location-combobox-menu').forEach(menu => { if (menu.id !== id + '-menu') menu.classList.add('d-none'); }); document.getElementById(id + '-menu')?.classList.toggle('d-none'); render(); search?.focus(); });
        results?.addEventListener('click', event => { const option = event.target.closest('[data-withdrawal-select]'); if (!option) return; select.value = option.dataset.value; select.dispatchEvent(new Event('change', { bubbles: true })); document.getElementById(id + '-menu')?.classList.add('d-none'); });
            select.addEventListener('change', () => { const selected = document.getElementById(id + '-selected'); if (selected) selected.textContent = select.value ? select.selectedOptions[0]?.textContent || '' : ''; render(); });
        render();
    };
    ['withdrawal-year', 'withdrawal-campus', 'withdrawal-grade-class'].forEach(id => reinforceSearchable(id, id));
    fetch('{{ route('student-withdrawals.options') }}').then(response => response.json()).then(data => {
        const activeReasons = data.reasons || [];
        const reasonRow = reasonPanel?.querySelector('.row.g-2');
        if (!reasonRow || !activeReasons.length) return;
        reasonRow.innerHTML = activeReasons.map(reason => '<div class="col-md-6"><label class="form-check"><input class="form-check-input withdrawal-reason-check" type="checkbox" value="' + escapeHtml(reason.key) + '" data-en="' + escapeHtml(reason.en) + '" data-kh="' + escapeHtml(reason.kh) + '"><span class="form-check-label"><span class="d-block school-profile-khmer">' + escapeHtml(reason.kh) + '</span>' + escapeHtml(reason.en) + '</span></label></div>').join('') + '<div class="col-md-6"><label class="form-check"><input class="form-check-input" type="checkbox" id="withdrawal-other-check"><span class="form-check-label">Other</span></label></div>';
    });
    if (reasonPanel && !field('withdrawal-new-school')) {
        reasonPanel.insertAdjacentHTML('beforeend', '<div class="row g-2 mt-3"><div class="col-md-6"><label class="form-label">New School</label><input id="withdrawal-new-school" class="form-control"></div><div class="col-md-6"><label class="form-label">New School Address</label><input id="withdrawal-new-school-address" class="form-control"></div><div class="col-md-6"><label class="form-label">Withdrawal Status</label><select id="withdrawal-dropout-type" class="form-select"><option value="official_leave">Will officially leave</option><option value="dropped_out">Has dropped out</option></select></div><div class="col-md-6"><label class="form-label">Additional Comments</label><input id="withdrawal-additional-comments" class="form-control"></div></div>');
    }
    const syncReasons = () => {
        const selected = Array.from(document.querySelectorAll('.withdrawal-reason-check:checked'));
        const otherEn = field('withdrawal-other-en')?.value.trim() || '';
        const otherKh = field('withdrawal-other-kh')?.value.trim() || '';
        const en = selected.map(item => item.dataset.en).concat(otherEn ? [otherEn] : []).filter(Boolean);
        const kh = selected.map(item => item.dataset.kh).concat(otherKh ? [otherKh] : []).filter(Boolean);
        if (field('withdrawal-reason-en')) field('withdrawal-reason-en').value = en.join('; ');
        if (field('withdrawal-reason-kh')) field('withdrawal-reason-kh').value = kh.join('; ');
        if (field('withdrawal-reason')) field('withdrawal-reason').value = en.join('; ');
    };
    document.addEventListener('change', event => {
        if (event.target.matches('.withdrawal-reason-check, #withdrawal-other-check')) {
            field('withdrawal-other-fields')?.classList.toggle('d-none', !field('withdrawal-other-check')?.checked);
            syncReasons();
        }
    });
    document.addEventListener('input', event => {
        if (event.target.matches('#withdrawal-other-en, #withdrawal-other-kh')) syncReasons();
    });
    const originalNew = document.getElementById('newWithdrawal');
    originalNew?.addEventListener('click', () => setTimeout(syncReasons, 0));
    form.onsubmit = async event => {
        event.preventDefault();
        syncReasons();
        const value = id => field(id)?.value || '';
        const type = value('withdrawal-type');
        const common = { withdrawal_date: value('withdrawal-date'), reason: value('withdrawal-reason'), reasons: Array.from(document.querySelectorAll('.withdrawal-reason-check:checked')).map(input => input.value), reason_kh: value('withdrawal-reason-kh'), other_reason_en: value('withdrawal-other-en'), other_reason_kh: value('withdrawal-other-kh'), new_school: value('withdrawal-new-school'), new_school_address: value('withdrawal-new-school-address'), dropout_type: value('withdrawal-dropout-type'), additional_comments: value('withdrawal-additional-comments'), notes: value('withdrawal-notes') };
        let endpoint, payload;
        if (type === 'student') { endpoint = 'withdraw'; payload = { ...common, enrollment_id: value('withdrawal-enrollment-id') }; }
        else { payload = { ...common, from_campus_id: value('withdrawal-campus'), from_academic_year_id: value('withdrawal-year'), from_grade_id: value('withdrawal-grade'), from_class_id: value('withdrawal-class') }; if (type === 'selected') { endpoint = 'withdraw-selected'; payload.enrollment_ids = Array.from(document.querySelectorAll('.withdrawal-student:checked')).map(input => Number(input.value)); } else endpoint = 'withdraw-class'; }
        const response = await fetch('{{ url('/student-withdrawals') }}/' + endpoint, { method: 'POST', headers: { Accept: 'application/json', 'Content-Type': 'application/json', 'X-CSRF-TOKEN': '{{ csrf_token() }}' }, body: JSON.stringify(payload) });
        const result = await response.json();
        if (!response.ok) { const error = field('withdrawal-error'); error.textContent = result.message || Object.values(result.errors || {})[0]?.[0] || 'Unable to withdraw student.'; error.classList.remove('d-none'); return; }
        bootstrap.Modal.getOrCreateInstance(document.getElementById('withdrawalModal')).hide();
        if (result.form_url && type === 'student') window.open(result.form_url, '_blank');
        window.location.reload();
    };
});
</script>
<script>
document.addEventListener('DOMContentLoaded', () => {
    const heading = document.querySelector('.withdrawal-reason-panel > .form-label, .withdrawal-reason-panel > h5');
    if (heading) heading.outerHTML = '<h4 class="mb-3 fw-bold">REASONS FOR WITHDRAWAL: <small class="text-secondary fw-normal">(Select all that apply)</small></h4>';
});
</script>
<style>
#withdrawalModal .modal-content { overflow: hidden; }
#withdrawalModal .modal-body { max-height: calc(100vh - 10rem); overflow-y: auto; }
</style>
@endpush
