@extends('layouts.app')
@section('title', 'Student Graduation')
@section('content')
<style>
    #graduation-year,
    #graduation-campus,
    #graduation-class,
    #graduation-search,
    #graduationModal input.form-control,
    #graduationModal select.form-select {
        height: 38px !important;
        min-height: 38px !important;
    }
    #graduation-search {
        width: min(420px, 35vw) !important;
        min-width: 320px;
    }
    @media (max-width: 767.98px) {
        #graduation-search { width: 100% !important; min-width: 0; }
    }
</style>
<div class="card"><div class="card-header d-flex align-items-center"><h3 class="card-title mb-0">Graduated Students</h3><button class="btn btn-primary ms-auto" id="newGraduation"><i class="ti ti-school icon"></i> Graduate Grade 12 Student</button></div><div class="card-body border-bottom py-3 d-flex gap-2"><select id="graduation-year" class="form-select w-auto"><option value="">All Academic Years</option></select><select id="graduation-campus" class="form-select w-auto"><option value="">All Campuses</option></select><select id="graduation-class" class="form-select w-auto"><option value="">All Classes</option></select><input id="graduation-search" class="form-control w-auto ms-auto" placeholder="Search student"></div><div class="table-responsive"><table class="table card-table"><thead><tr><th>Student</th><th>Academic Year</th><th>Campus</th><th>Class</th><th>Group</th><th>Graduation Date</th><th>Certificate</th><th>Alumni</th><th>Changed By</th></tr></thead><tbody id="graduationTable"><tr><td colspan="9" class="text-center">Loading...</td></tr></tbody></table></div><div class="card-footer"><div id="graduation-pagination-container"></div></div></div>
<div class="modal modal-blur fade" id="graduationModal" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><form id="graduationForm"><div class="modal-header"><h3 class="modal-title">Graduate Grade 12 Student</h3><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="alert alert-danger d-none" id="graduationError"></div><label class="form-label">Grade 12 Student *</label><select id="graduation-enrollment" class="form-select mb-3" required></select><div class="small text-secondary mb-3" id="graduation-current"></div><label class="form-label">Graduation Date *</label><input type="date" id="graduation-date" class="form-control mb-3" required><label class="form-label">Certificate Number</label><input id="certificate-number" class="form-control mb-3"><label class="form-check"><input type="checkbox" id="is-alumni" class="form-check-input"><span class="form-check-label">Mark as Alumni</span></label><label class="form-label mt-3">Notes</label><textarea id="graduation-notes" class="form-control" rows="3"></textarea></div><div class="modal-footer"><button type="button" class="btn me-auto" data-bs-dismiss="modal">Cancel</button><button class="btn btn-primary">Graduate Student</button></div></form></div></div></div>
<script>
(() => {
    window.addEventListener('load', () => {
        const csrf = document.querySelector('meta[name="csrf-token"]')?.content || '';
        const field = (id) => document.getElementById(id);
        const modal = bootstrap.Modal.getOrCreateInstance(field('graduationModal'));
        let options = {};
        const esc = (value = '') => String(value).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');
        const setupScope = () => { if (field('graduation-scope')) return; const enrollment = field('graduation-enrollment'); const label = enrollment.previousElementSibling; const current = field('graduation-current'); label.classList.add('graduation-student-field'); enrollment.classList.add('graduation-student-field'); current.classList.add('graduation-student-field'); label.insertAdjacentHTML('beforebegin', '<label class="form-label graduation-scope-field">Graduation Scope *</label><select id="graduation-scope" class="form-select mb-3 graduation-scope-field"><option value="student">Individual Student</option><option value="class">Entire Class</option><option value="campus">Entire Campus</option></select>'); current.insertAdjacentHTML('afterend', '<div id="graduation-batch-block" class="d-none"><label class="form-label">Academic Year *</label><select id="batch-year" class="form-select mb-3"></select><label class="form-label">Campus *</label><select id="batch-campus" class="form-select mb-3"></select><div id="batch-class-block"><label class="form-label">Class *</label><select id="batch-class" class="form-select mb-3"></select></div></div>'); field('graduation-scope').onchange = () => { const batch = field('graduation-scope').value !== 'student'; document.querySelectorAll('.graduation-student-field').forEach((element) => element.classList.toggle('d-none', batch)); field('graduation-batch-block').classList.toggle('d-none', !batch); field('batch-class-block').classList.toggle('d-none', field('graduation-scope').value !== 'class'); enrollment.required = !batch; }; field('batch-campus').onchange = () => refreshClasses(field('batch-campus').value, field('batch-year').value, 'batch-class', false); field('batch-year').onchange = async () => { await refreshCampuses(field('batch-year').value, false, 'batch-campus'); await refreshClasses(field('batch-campus').value, field('batch-year').value, 'batch-class', false); };
        };
        const fill = (id, items, label, all = true) => { field(id).innerHTML = `<option value="">${all ? `All ${label}` : `Select ${label}`}</option>` + items.map((item) => `<option value="${item.id}">${esc(item[label === 'Academic Years' ? 'academic_year' : label === 'Campuses' ? 'campus_name_en' : 'class_name'])}</option>`).join(''); };
        const loadOptions = async (list = false) => { options = await (await fetch(`/student-graduations/options${list ? '?list=1' : ''}`)).json(); fill('graduation-year', options.academicYears || [], 'Academic Years'); fill('graduation-campus', options.campuses || [], 'Campuses'); fill('graduation-class', options.classes || [], 'Classes'); setupScope(); fill('batch-year', options.academicYears || [], 'Academic Years'); fill('batch-campus', options.campuses || [], 'Campuses'); fill('batch-class', options.classes || [], 'Classes', false); field('graduation-enrollment').innerHTML = '<option value="">Select Grade 12 student</option>' + (options.enrollments || []).map((item) => `<option value="${item.id}" data-info="${esc(`${item.academic_year?.academic_year || '-'} | ${item.campus?.campus_name_en || '-'} | Class ${item.school_class?.class_name || '-'} | Group ${item.session?.session_short_name || '-'}`)}">${esc(`${item.student?.student_id || item.student?.student_no || ''} - ${item.student?.first_name_en || ''} ${item.student?.last_name_en || ''}`)}</option>`).join(''); };
        const refreshCampuses = async (yearId, list, targetId) => { const result = await (await fetch(`/student-graduations/options?academic_year_id=${encodeURIComponent(yearId || '')}${list ? '&list=1' : ''}`)).json(); fill(targetId, result.campuses || [], 'Campuses'); };
        const refreshClasses = async (campusId, yearId, targetId, list = true) => { const result = await (await fetch(`/student-graduations/options?campus_id=${encodeURIComponent(campusId || '')}&academic_year_id=${encodeURIComponent(yearId || '')}${list ? '&list=1' : ''}`)).json(); fill(targetId, result.classes || [], 'Classes', targetId === 'batch-class' ? false : true); };
        const render = async (page = 1) => { const query = new URLSearchParams({ page, perPage: 10, academic_year_id: field('graduation-year').value, campus_id: field('graduation-campus').value, class_id: field('graduation-class').value, search: field('graduation-search').value }); const result = await (await fetch(`/student-graduations/fetch?${query}`)).json(); field('graduationTable').innerHTML = result.data?.length ? result.data.map((item) => `<tr><td>${esc(`${item.student?.student_no || ''} - ${item.student?.first_name_en || ''} ${item.student?.last_name_en || ''}`)}</td><td>${esc(item.academic_year?.academic_year || '-')}</td><td>${esc(item.campus?.campus_name_en || '-')}</td><td>${esc(item.school_class?.class_name || '-')}</td><td>${esc(item.session?.session_short_name || '-')}</td><td>${esc(item.graduation_date || '-')}</td><td>${esc(item.certificate_number || '-')}</td><td>${item.is_alumni ? 'Yes' : 'No'}</td><td>${esc(item.changed_by?.name || 'System')}</td></tr>`).join('') : '<tr><td colspan="9" class="text-center">No graduated students found.</td></tr>'; };
        field('graduation-year').onchange = async () => { await refreshCampuses(field('graduation-year').value, true, 'graduation-campus'); await refreshClasses(field('graduation-campus').value, field('graduation-year').value, 'graduation-class', true); await render(); }; field('graduation-campus').onchange = async () => { await refreshClasses(field('graduation-campus').value, field('graduation-year').value, 'graduation-class', true); await render(); }; field('graduation-class').onchange = () => render(); field('graduation-search').oninput = () => render();
        field('graduation-enrollment').onchange = () => { const option = field('graduation-enrollment').selectedOptions[0]; field('graduation-current').textContent = option?.dataset.info || ''; };
        field('newGraduation').onclick = async () => { await loadOptions(false); field('graduationForm').reset(); field('graduation-scope').value = 'student'; field('graduation-scope').dispatchEvent(new Event('change')); field('graduation-date').value = new Date().toISOString().slice(0,10); field('graduation-current').textContent = ''; field('graduationError').classList.add('d-none'); modal.show(); };
        field('graduationForm').onsubmit = async (event) => { event.preventDefault(); const scope = field('graduation-scope').value; const payload = { graduation_date: field('graduation-date').value, certificate_number: field('certificate-number').value, is_alumni: field('is-alumni').checked ? 1 : 0, notes: field('graduation-notes').value }; const endpoint = scope === 'student' ? 'graduate' : 'graduate-batch'; if (scope === 'student') payload.enrollment_id = field('graduation-enrollment').value; else { payload.scope = scope; payload.academic_year_id = field('batch-year').value; payload.campus_id = field('batch-campus').value; payload.class_id = scope === 'class' ? field('batch-class').value : ''; } const response = await fetch(`/student-graduations/${endpoint}`, { method: 'POST', headers: { Accept: 'application/json', 'Content-Type': 'application/json', 'X-CSRF-TOKEN': csrf }, body: JSON.stringify(payload) }); const result = await response.json(); if (!response.ok) { field('graduationError').textContent = result.message || 'Unable to graduate student.'; field('graduationError').classList.remove('d-none'); return; } modal.hide(); await render(); };
        loadOptions(true).then(render);
    });
})();
</script>
@endsection
