@extends('layouts.app')
@section('title','Student Documents')
@section('page-header')<div class="container-fluid"><div class="row g-2 align-items-center"><div class="col"><div class="page-pretitle">Students</div><h2 class="page-title">Student Documents</h2></div><div class="col-auto"><button class="btn btn-primary" id="newStudentDocument"><i class="ti ti-upload me-1"></i> Upload Document</button></div></div></div>@endsection
@section('content')
<div class="card"><div class="card-header"><h3 class="card-title">Student Document Records</h3></div><div class="card-body border-bottom"><label class="form-label">Student *</label><input id="student-document-search" class="form-control mb-1" placeholder="Search student ID or name"><select id="student-document-student" class="form-select"></select></div><div class="table-responsive"><table class="table card-table"><thead><tr><th>Document Type</th><th>Title</th><th>Number</th><th>File</th><th class="text-center">Actions</th></tr></thead><tbody id="student-documents-table"><tr><td colspan="5" class="text-center">Select a student.</td></tr></tbody></table></div></div>
<div class="modal modal-blur fade" id="studentDocumentModal" tabindex="-1"><div class="modal-dialog modal-dialog-centered modal-lg"><div class="modal-content"><form id="studentDocumentForm"><div class="modal-header"><h3 class="modal-title">Upload Student Document</h3><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="alert alert-danger d-none" id="student-document-error"></div><input type="hidden" id="document-student-id"><div class="row g-3"><div class="col-md-6"><label class="form-label">Document Type *</label><select id="document-type-id" class="form-select" required></select></div><div class="col-md-6"><label class="form-label">Title</label><input id="document-title" class="form-control"></div><div class="col-md-6"><label class="form-label">Document Number</label><input id="document-number" class="form-control"></div><div class="col-12"><label class="form-label">File * (PDF, JPG, PNG, DOC, DOCX)</label><input type="file" id="document-file" class="form-control" accept=".pdf,.jpg,.jpeg,.png,.doc,.docx" required></div><div class="col-12"><label class="form-label">Description</label><textarea id="document-description" class="form-control" rows="3"></textarea></div></div></div><div class="modal-footer"><button type="button" class="btn me-auto" data-bs-dismiss="modal">Cancel</button><button class="btn btn-primary">Upload</button></div></form></div></div></div>
@push('scripts')
<script>
document.addEventListener('DOMContentLoaded', () => {
    const $ = id => document.getElementById(id), state = {};
    const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
    const studentLabel = item => `${item.student_id || item.student_no || ''} - ${item.first_name_en || ''} ${item.last_name_en || ''}`;
    const loadOptions = async () => { Object.assign(state, await (await fetch('{{ route('student-documents.options') }}?search=' + encodeURIComponent($('student-document-search').value))).json()); $('student-document-student').innerHTML = '<option value="">Select Student</option>' + (state.students || []).map(item => `<option value="${item.id}">${esc(studentLabel(item))}</option>`).join(''); $('document-type-id').innerHTML = '<option value="">Select Document Type</option>' + (state.types || []).map(item => `<option value="${item.id}">${esc(item.name_kh || '')}${item.name_kh ? ' / ' : ''}${esc(item.name_en)}</option>`).join(''); };
    const loadDocuments = async () => { const id = $('student-document-student').value; if (!id) { $('student-documents-table').innerHTML = '<tr><td colspan="5" class="text-center">Select a student.</td></tr>'; return; } const documents = await (await fetch('/student-documents/fetch/' + id)).json(); $('student-documents-table').innerHTML = documents.length ? documents.map(doc => `<tr><td>${esc(doc.type?.name_en || doc.document_type || '-')}<div class="small school-profile-khmer">${esc(doc.type?.name_kh || '')}</div></td><td>${esc(doc.title || '-')}</td><td>${esc(doc.document_number || '-')}</td><td>${doc.file_path ? `<a href="/student-documents/${doc.id}/download">${esc(doc.original_filename || 'Download')}</a>` : '-'}</td><td class="text-center"><button class="btn btn-sm btn-outline-danger" data-delete="${doc.id}"><i class="ti ti-trash"></i></button></td></tr>`).join('') : '<tr><td colspan="5" class="text-center">No documents found.</td></tr>'; $('student-documents-table').querySelectorAll('[data-delete]').forEach(button => button.onclick = async () => { if (!confirm('Delete this document?')) return; await fetch('/student-documents/' + button.dataset.delete, { method: 'DELETE', headers: { Accept: 'application/json', 'X-CSRF-TOKEN': '{{ csrf_token() }}' } }); loadDocuments(); }); };
    $('student-document-search').oninput = loadOptions; $('student-document-student').onchange = loadDocuments;
    $('newStudentDocument').onclick = () => { if (!$('student-document-student').value) return alert('Please select a student first.'); $('studentDocumentForm').reset(); $('document-student-id').value = $('student-document-student').value; bootstrap.Modal.getOrCreateInstance($('studentDocumentModal')).show(); };
    $('studentDocumentForm').onsubmit = async event => { event.preventDefault(); const form = new FormData(); form.append('student_id', $('document-student-id').value); form.append('document_type_id', $('document-type-id').value); form.append('title', $('document-title').value); form.append('document_number', $('document-number').value); form.append('description', $('document-description').value); form.append('file', $('document-file').files[0]); const response = await fetch('{{ route('student-documents.save') }}', { method: 'POST', headers: { Accept: 'application/json', 'X-CSRF-TOKEN': '{{ csrf_token() }}' }, body: form }); const result = await response.json(); if (!response.ok) { $('student-document-error').textContent = result.message || Object.values(result.errors || {})[0]?.[0] || 'Unable to upload document.'; $('student-document-error').classList.remove('d-none'); return; } bootstrap.Modal.getOrCreateInstance($('studentDocumentModal')).hide(); loadDocuments(); };
    loadOptions();
});
</script>
@endpush
@endsection
