import { renderPagination, renderPageInfo } from "./helpers/pagination.js";
import { showSuccess, showConfirm, showError } from "./helpers/sweet-alert2.js";
const csrf = document.querySelector('meta[name="csrf-token"]')?.content;
const form = document.getElementById("groupForm"), modal = new bootstrap.Modal(document.getElementById("groupModal")), table = document.getElementById("groupsTable"), search = document.getElementById("groups-search"), perPage = document.getElementById("groups-per-page"), submit = document.getElementById("groupSubmit"), title = document.getElementById("groupModalTitle"); let rows = [];
const alertError = message => { const a = form.querySelector("[data-alert]"); a.textContent = message || "Please correct the errors below."; a.classList.remove("d-none"); };
const loadOptions = async () => { const j = await (await fetch("/groups/options")).json(); class_id.innerHTML = `<option value="">Select Class</option>` + j.classes.map(x => `<option value="${x.id}">${x.class_name}</option>`).join(""); };
const openCreate = async () => { form.reset(); form.querySelector("[data-alert]").classList.add("d-none"); group_id.value = ""; title.textContent = "Create Group"; submit.textContent = "Create"; await loadOptions(); modal.show(); };
const openEdit = async id => { const row = rows.find(x => x.id === id); if (!row) return; await openCreate(); group_id.value = row.id; class_id.value = row.class_id; group_name.value = row.group_name; group_order.value = row.group_order ?? ""; status.value = row.status ? "1" : "0"; title.textContent = "Edit Group"; submit.textContent = "Update"; };
form.addEventListener("submit", async e => { e.preventDefault(); submit.disabled = true; try { const r = await fetch("/groups/save", { method: "POST", headers: { Accept: "application/json", "X-CSRF-TOKEN": csrf }, body: new FormData(form) }), j = await r.json(); if (r.status === 422) return alertError(j.message); if (!r.ok) throw Error(j.message); modal.hide(); showSuccess("Saved", j.message); fetchRows(); } catch (e) { alertError(e.message); } finally { submit.disabled = false; } });
const remove = async id => { if (!(await showConfirm("Delete Group", "Are you sure?", "Delete", "Cancel")).isConfirmed) return; const r = await fetch(`/groups/delete/${id}`, { method: "DELETE", headers: { Accept: "application/json", "X-CSRF-TOKEN": csrf } }), j = await r.json(); r.ok ? (showSuccess("Deleted", j.message), fetchRows()) : showError("Error", j.message); };
async function fetchRows(page = 1) { const r = await fetch(`/groups/fetch?page=${page}&perPage=${perPage.value}&search=${encodeURIComponent(search.value)}`), j = await r.json(); rows = j.data; table.innerHTML = rows.length ? rows.map(x => `<tr><td>${x.group_name}</td><td>${x.school_class?.class_name ?? "-"}</td><td>${x.group_order ?? ""}</td><td>${x.status ? "<span class='badge bg-success-lt'>Active</span>" : "<span class='badge bg-danger-lt'>Inactive</span>"}</td><td><button class="btn btn-primary btn-sm" onclick="groupsPage.edit(${x.id})">Edit</button> <button class="btn btn-danger btn-sm" onclick="groupsPage.remove(${x.id})">Delete</button></td></tr>`).join("") : `<tr><td colspan="5" class="text-center">No groups found.</td></tr>`; renderPagination(j, "groups-pagination-container", "groups-per-page", fetchRows); renderPageInfo(j); }
document.getElementById("newGroup").onclick = openCreate; perPage.onchange = () => fetchRows(); search.onkeyup = () => fetchRows(); loadOptions(); fetchRows(); window.groupsPage = { edit: openEdit, remove };
