import { renderPagination, renderPageInfo } from "./helpers/pagination.js";
import { showSuccess, showConfirm, showError } from "./helpers/sweet-alert2.js";
const csrf = document.querySelector('meta[name="csrf-token"]')?.content;
const form = document.getElementById("programForm"), modal = new bootstrap.Modal(document.getElementById("programModal")), table = document.getElementById("programsTable"), search = document.getElementById("programs-search"), perPage = document.getElementById("programs-per-page"), submit = document.getElementById("programSubmit"), title = document.getElementById("programModalTitle");
let rows = [];
const alertError = (message) => { const a = form.querySelector("[data-alert]"); a.textContent = message || "Please correct the errors below."; a.classList.remove("d-none"); };
const loadOptions = async () => { const j = await (await fetch("/programs/options")).json(); academic_year_id.innerHTML = `<option value="">All Academic Years</option>` + j.academicYears.map(x => `<option value="${x.id}">${x.academic_year}</option>`).join(""); education_level_id.innerHTML = `<option value="">Select Education Level</option>` + j.levels.map(x => `<option value="${x.id}">${x.level_name}</option>`).join(""); };
const openCreate = async () => { form.reset(); form.querySelector("[data-alert]").classList.add("d-none"); program_id.value = ""; title.textContent = "Create Program"; submit.textContent = "Create"; await loadOptions(); modal.show(); };
const openEdit = async (id) => { const row = rows.find(x => x.id === id); if (!row) return; await openCreate(); program_id.value = row.id; academic_year_id.value = row.academic_year_id ?? ""; education_level_id.value = row.education_level_id; program_name.value = row.program_name; program_code.value = row.program_code; description.value = row.description ?? ""; status.value = row.status ? "1" : "0"; title.textContent = "Edit Program"; submit.textContent = "Update"; };
form.addEventListener("submit", async (e) => { e.preventDefault(); submit.disabled = true; try { const r = await fetch("/programs/save", { method: "POST", headers: { Accept: "application/json", "X-CSRF-TOKEN": csrf }, body: new FormData(form) }), j = await r.json(); if (r.status === 422) return alertError(j.message); if (!r.ok) throw Error(j.message); modal.hide(); showSuccess("Saved", j.message); fetchRows(); } catch (e) { alertError(e.message); } finally { submit.disabled = false; } });
const remove = async (id) => { if (!(await showConfirm("Delete Program", "Are you sure?", "Delete", "Cancel")).isConfirmed) return; const r = await fetch(`/programs/delete/${id}`, { method: "DELETE", headers: { Accept: "application/json", "X-CSRF-TOKEN": csrf } }), j = await r.json(); r.ok ? (showSuccess("Deleted", j.message), fetchRows()) : showError("Error", j.message); };
async function fetchRows(page = 1) { const r = await fetch(`/programs/fetch?page=${page}&perPage=${perPage.value}&search=${encodeURIComponent(search.value)}`), j = await r.json(); rows = j.data; table.innerHTML = rows.length ? rows.map(x => `<tr><td>${x.program_name}</td><td>${x.program_code}</td><td>${x.academic_year?.academic_year ?? "-"}</td><td>${x.education_level?.level_name ?? "-"}</td><td>${x.status ? "<span class='badge bg-success-lt'>Active</span>" : "<span class='badge bg-danger-lt'>Inactive</span>"}</td><td><button class="btn btn-primary btn-sm" onclick="programsPage.edit(${x.id})">Edit</button> <button class="btn btn-danger btn-sm" onclick="programsPage.remove(${x.id})">Delete</button></td></tr>`).join("") : `<tr><td colspan="6" class="text-center">No programs found.</td></tr>`; renderPagination(j, "programs-pagination-container", "programs-per-page", fetchRows); renderPageInfo(j); }
document.getElementById("newProgram").onclick = openCreate;
perPage.onchange = () => fetchRows(); search.onkeyup = () => fetchRows(); loadOptions(); fetchRows(); window.programsPage = { edit: openEdit, remove };
