data-g12-font-key="{{ $fontKey }}"
data-g12-layout-key="{{ $fontKey }}"
data-g12-font-name="{{ $field['font'] }}"
data-g12-font-family="{{ \App\Support\G12CertificateTypography::family($field['font'], false) }}"
data-g12-font-size="{{ $field['size'] }}"
data-g12-font-color="{{ $field['color'] }}"
data-g12-source="{{ $field['text'] }}"
data-g12-bold="{{ $field['bold'] ? '1' : '0' }}"
data-g12-bold-first-line="{{ $field['bold_first_line'] ? '1' : '0' }}"
data-g12-align="{{ $field['align'] }}"
data-g12-x="{{ $field['x'] }}"
data-g12-y="{{ $field['y'] }}"
data-g12-width="{{ $field['width'] }}"
@if($fontKey === 'title') data-g12-curve="{{ $field['curve'] ?? 26 }}" @endif
