data-g9-font-key="{{ $fontKey }}"
data-g9-layout-key="{{ $fontKey }}"
data-g9-font-name="{{ $field['font'] }}"
data-g9-font-family="{{ \App\Support\G9CertificateTypography::family($field['font'], false) }}"
data-g9-font-size="{{ $field['size'] }}"
data-g9-font-color="{{ $field['color'] }}"
data-g9-source="{{ $field['text'] }}"
data-g9-bold="{{ $field['bold'] ? '1' : '0' }}"
data-g9-bold-first-line="{{ $field['bold_first_line'] ? '1' : '0' }}"
data-g9-align="{{ $field['align'] }}"
data-g9-x="{{ $field['x'] }}"
data-g9-y="{{ $field['y'] }}"
data-g9-width="{{ $field['width'] }}"
@if($fontKey === 'title') data-g9-curve="{{ $field['curve'] ?? 26 }}" @endif
