@extends('layouts.app')
@section('title','Reports')
@section('page-header')<div class="container-fluid"><div class="row g-2 align-items-center"><div class="col"><div class="page-pretitle">Management</div><h2 class="page-title">Reports</h2></div></div></div>@endsection
@section('content')
<div class="row g-3 reports-workspace"><div class="col-lg-3"><div class="card reports-tabs-card"><div class="card-header"><h3 class="card-title">Report Types</h3></div><div class="list-group list-group-flush">@foreach($reportTypes as $key=>$label)<a href="{{ route('reports.index',['type'=>$key]+request()->except('type')) }}" class="list-group-item list-group-item-action {{ $type===$key?'active':'' }}"><i class="ti {{ ['student-list'=>'ti-list-details','student-contact-list'=>'ti-address-book','score-list'=>'ti-notes','attendance-list'=>'ti-calendar-check','student-statistics'=>'ti-chart-bar'][$key] }} me-2"></i>{{ $label }}</a>@endforeach</div></div></div>
<div class="col-lg-9"><div class="card mb-3"><div class="card-header"><h3 class="card-title">{{ $reportTypes[$type] }}</h3></div><form method="get" action="{{ route('reports.index') }}"><input type="hidden" name="type" value="{{ $type }}"><div class="card-body"><div class="{{ $type==='student-list' ? 'report-student-filter-row' : 'row g-3' }}">
@if($type==='student-list')
<div class="report-filter-field"><label class="form-label">Period</label><select name="period_type" class="form-select"><option value="all" @selected(($filters['period_type']??'all')==='all')>Regular + Summer</option><option value="regular" @selected(($filters['period_type']??'')==='regular')>Regular</option><option value="summer" @selected(($filters['period_type']??'')==='summer')>Summer</option></select></div>
<div class="report-filter-field"><label class="form-label">Academic Year</label><div class="report-filter-combobox" data-target="reportAcademicYearValue"><button type="button" class="report-filter-toggle"><span>{{ $academicYears->firstWhere('id',(int)($filters['academic_year_id']??0))?->academic_year ?: '' }}</span><i class="ti ti-chevron-down"></i></button><div class="report-filter-menu"><input type="search" class="form-control report-filter-search" placeholder="Search Academic Year"><div class="report-filter-options"><button type="button" data-value="">All Academic Years</button>@foreach($academicYears as $year)<button type="button" data-value="{{ $year->id }}">{{ $year->academic_year }}</button>@endforeach</div></div></div><input type="hidden" name="academic_year_id" id="reportAcademicYearValue" value="{{ $filters['academic_year_id']??'' }}"></div>
<div class="report-filter-field"><label class="form-label">Campus</label><div class="report-filter-combobox" data-target="reportCampusValue"><button type="button" class="report-filter-toggle"><span>{{ $campuses->firstWhere('id',(int)($filters['campus_id']??0))?->campus_name_en ?: '' }}</span><i class="ti ti-chevron-down"></i></button><div class="report-filter-menu"><input type="search" class="form-control report-filter-search" placeholder="Search Campus"><div class="report-filter-options"><button type="button" data-value="">All Campuses</button>@foreach($campuses as $campus)<button type="button" data-value="{{ $campus->id }}">{{ $campus->campus_name_en }}</button>@endforeach</div></div></div><input type="hidden" name="campus_id" id="reportCampusValue" value="{{ $filters['campus_id']??'' }}"></div>
<div class="report-filter-field"><label class="form-label">Grade + Class</label><div class="report-filter-combobox" data-target="reportGradeClassValue"><button type="button" class="report-filter-toggle"><span>{{ data_get(collect($gradeClassOptions)->firstWhere('value',$filters['grade_class']??''), 'label', '') }}</span><i class="ti ti-chevron-down"></i></button><div class="report-filter-menu"><input type="search" class="form-control report-filter-search" placeholder="Search Grade + Class"><div class="report-filter-options"><button type="button" data-value="">All Grades + Classes</button>@foreach($gradeClassOptions as $option)<button type="button" data-value="{{ $option['value'] }}">{{ $option['label'] }}</button>@endforeach</div></div></div><input type="hidden" name="grade_class" id="reportGradeClassValue" value="{{ $filters['grade_class']??'' }}"></div>
<div class="report-filter-field"><label class="form-label">Group</label><div class="report-filter-combobox" data-target="reportGroupValue"><button type="button" class="report-filter-toggle"><span>{{ $groupOptions->firstWhere('session_id',(int)($filters['session_id']??0))?->session_short_name ?: '' }}</span><i class="ti ti-chevron-down"></i></button><div class="report-filter-menu"><input type="search" class="form-control report-filter-search" placeholder="Search Group"><div class="report-filter-options"><button type="button" data-value="">All Groups</button>@foreach($groupOptions as $group)<button type="button" data-value="{{ $group->session_id }}">{{ $group->session_short_name }}</button>@endforeach</div></div></div><input type="hidden" name="session_id" id="reportGroupValue" value="{{ $filters['session_id']??'' }}"></div><div class="report-filter-actions"><a class="btn btn-outline-secondary" href="{{ route('reports.index',['type'=>'student-list']) }}"><i class="ti ti-rotate-2 me-1"></i>Refresh / Clear Filters</a></div>
@else
<div class="col-md-4"><label class="form-label">Period</label><select name="period_type" class="form-select"><option value="all" @selected(($filters['period_type']??'all')==='all')>Regular + Summer</option><option value="regular" @selected(($filters['period_type']??'')==='regular')>Regular</option><option value="summer" @selected(($filters['period_type']??'')==='summer')>Summer</option></select></div>
<div class="col-md-4"><label class="form-label">Academic Year</label><select name="academic_year_id" class="form-select"><option value="">All Academic Years</option>@foreach($academicYears as $year)<option value="{{ $year->id }}" @selected(($filters['academic_year_id']??'')==$year->id)>{{ $year->academic_year }}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">Campus</label><select name="campus_id" class="form-select"><option value="">All Campuses</option>@foreach($campuses as $campus)<option value="{{ $campus->id }}" @selected(($filters['campus_id']??'')==$campus->id)>{{ $campus->campus_name_en }}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">Grade</label><select name="grade_id" class="form-select"><option value="">All Grades</option>@foreach($grades as $grade)<option value="{{ $grade->id }}" @selected(($filters['grade_id']??'')==$grade->id)>{{ $grade->grade }}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">Class ID</label><input name="class_id" type="number" min="1" class="form-control" value="{{ $filters['class_id']??'' }}"></div>@if($type==='attendance-list')<div class="col-md-4"><label class="form-label">Month</label><input name="month" type="month" class="form-control" value="{{ $filters['month'] }}"></div>@endif @if($type==='score-list')<div class="col-md-4"><label class="form-label">Score Columns</label><input name="score_columns" type="number" min="1" max="12" class="form-control" value="{{ $filters['score_columns'] }}"></div>@endif
@endif
@if($type==='student-list')<div class="row g-3 mt-2 report-print-options"><div class="col-md-3"><label class="form-label">Print Format</label><select name="print_format" class="form-select"><option value="internal" @selected(($filters['print_format']??'internal')==='internal')>Internal Student List</option><option value="moeys" @selected(($filters['print_format']??'')==='moeys')>MoEYS Khmer List</option></select></div><div class="col-md-3"><label class="form-label">Print Scope</label><select name="print_scope" class="form-select"><option value="selected_class" @selected(($filters['print_scope']??'selected_class')==='selected_class')>Selected Class</option><option value="selected_classes" @selected(($filters['print_scope']??'')==='selected_classes')>Selected Classes</option><option value="all_classes" @selected(($filters['print_scope']??'')==='all_classes')>All Classes by Campus</option></select></div><div class="col-md-3"><label class="form-label">Classes to Print</label><select name="print_grade_classes[]" class="form-select" multiple size="3">@foreach($gradeClassOptions as $option)<option value="{{ $option['value'] }}" @selected(in_array($option['value'], $filters['print_grade_classes']??[], true))>{{ $option['label'] }}</option>@endforeach</select><div class="form-hint">Use Ctrl/Cmd to select multiple classes.</div></div></div>@endif
</div></div><div class="card-footer d-flex gap-2"><button class="btn btn-primary"><i class="ti ti-refresh me-1"></i>Generate Report</button><a class="btn btn-outline-primary report-print-link" target="_blank" href="{{ route('reports.show',$type) . '?' . http_build_query($filters) }}"><i class="ti ti-printer me-1"></i>Print</a><a class="btn btn-outline-success" href="{{ route('reports.excel',$type) . '?' . http_build_query($filters) }}"><i class="ti ti-file-spreadsheet me-1"></i>Excel</a></div></form></div>
<div class="card"><div class="card-header"><h3 class="card-title">Report Preview</h3></div><div class="card-body"><div class="table-responsive">@include('reports._table')</div></div></div></div></div>
@if($type==='student-list')<style>.report-student-filter-row{display:flex;flex-wrap:nowrap;gap:.75rem;align-items:flex-end;overflow:visible}.report-filter-field{flex:1 1 0;min-width:180px}.report-filter-field .form-label{display:block}.report-filter-combobox{position:relative}.report-filter-toggle{width:100%;min-height:40px;display:flex;align-items:center;justify-content:space-between;gap:.5rem;padding:.5rem .75rem;border:1px solid var(--tblr-border-color,#d9e1e8);border-radius:4px;background:var(--tblr-bg-forms,#fff);color:var(--tblr-body-color,#1e293b);text-align:left}.report-filter-actions{flex:0 0 auto;padding-bottom:0}.report-filter-menu{position:absolute;z-index:1050;top:calc(100% + 4px);left:0;width:100%;min-width:220px;padding:.5rem;background:var(--tblr-bg-surface,#fff);border:1px solid var(--tblr-border-color,#d9e1e8);border-radius:6px;box-shadow:0 8px 24px #0003;display:none}.report-filter-combobox.is-open .report-filter-menu{display:block}.report-filter-options{max-height:220px;overflow-y:auto;margin-top:.4rem}.report-filter-options button{display:block;width:100%;border:0;background:transparent;color:inherit;text-align:left;padding:.5rem;border-radius:4px}.report-filter-options button:hover,.report-filter-options button.is-selected{background:var(--tblr-primary-lt,#e9f2ff)}@media(max-width:991px){.report-student-filter-row{flex-wrap:wrap}.report-filter-field{flex:1 1 calc(50% - .75rem)}.report-filter-actions{flex-basis:100%}}@media(max-width:575px){.report-filter-field{flex-basis:100%}}</style><script>document.querySelectorAll('.report-filter-combobox').forEach(box=>{const toggle=box.querySelector('.report-filter-toggle'),menu=box.querySelector('.report-filter-menu'),search=box.querySelector('.report-filter-search'),target=document.getElementById(box.dataset.target),options=[...box.querySelectorAll('.report-filter-options button')];toggle.addEventListener('click',e=>{e.stopPropagation();document.querySelectorAll('.report-filter-combobox.is-open').forEach(other=>{if(other!==box)other.classList.remove('is-open')});box.classList.toggle('is-open');if(box.classList.contains('is-open')){search.value='';options.forEach(option=>option.hidden=false);search.focus()}});search.addEventListener('input',()=>{const query=search.value.trim().toLowerCase();options.forEach(option=>option.hidden=query && !option.textContent.trim().toLowerCase().includes(query))});options.forEach(option=>option.addEventListener('click',()=>{target.value=option.dataset.value;toggle.querySelector('span').textContent=option.textContent.trim();options.forEach(item=>item.classList.toggle('is-selected',item===option));box.classList.remove('is-open')}))});document.addEventListener('click',()=>document.querySelectorAll('.report-filter-combobox.is-open').forEach(box=>box.classList.remove('is-open')));</script>
@endif
@if($type==='student-list')<script>document.querySelectorAll('.report-filter-combobox').forEach(box=>{const target=document.getElementById(box.dataset.target);if(!target||!['reportAcademicYearValue','reportCampusValue','reportGradeClassValue'].includes(target.id))return;box.querySelectorAll('.report-filter-options button').forEach(option=>option.addEventListener('click',()=>setTimeout(()=>box.closest('form')?.requestSubmit(),0)))});</script>@endif
@if($type==='student-list')<script>const reportPrintLink=document.querySelector('.report-print-link');if(reportPrintLink){reportPrintLink.addEventListener('click',()=>{const url=new URL(reportPrintLink.href);new FormData(reportPrintLink.closest('form')).forEach((value,key)=>url.searchParams.append(key,value));reportPrintLink.href=url.toString()})}</script>@endif
<style>
    .report-student-filter-row .report-filter-field {
        display: flex !important;
        flex-direction: column !important;
        align-items: stretch !important;
    }
    .report-student-filter-row .report-filter-field > .form-label {
        position: static !important;
        display: block !important;
        transform: none !important;
        height: auto !important;
        margin: 0 0 .5rem !important;
        line-height: 1.25 !important;
    }
    .report-student-filter-row .report-filter-combobox {
        width: 100%;
    }
    .report-student-filter-row {
        flex-wrap: wrap !important;
    }
    .report-student-filter-row > .report-print-options {
        flex: 0 0 100% !important;
        width: 100% !important;
        max-width: 100% !important;
        margin-left: 0 !important;
        margin-right: 0 !important;
    }
    .report-student-filter-row > .report-print-options > [class*="col-"] {
        flex: 0 0 25% !important;
        max-width: 25% !important;
    }
    .report-class-picker { position: relative; }
    .report-class-picker-toggle { width: 100%; min-height: 40px; display: flex; align-items: center; justify-content: space-between; gap: .5rem; padding: .5rem .75rem; border: 1px solid var(--tblr-border-color,#d9e1e8); border-radius: 4px; background: var(--tblr-bg-forms,#fff); color: var(--tblr-body-color,#1e293b); text-align: left; }
    .report-class-picker-menu { position: absolute; z-index: 1060; top: calc(100% + 4px); left: 0; width: 100%; min-width: 240px; padding: .5rem; background: var(--tblr-bg-surface,#fff); border: 1px solid var(--tblr-border-color,#d9e1e8); border-radius: 6px; box-shadow: 0 8px 24px #0003; display: none; }
    .report-class-picker.is-open .report-class-picker-menu { display: block; }
    .report-class-picker-options { max-height: 220px; overflow-y: auto; margin-top: .4rem; }
    .report-class-picker-option { display: flex; align-items: center; gap: .5rem; width: 100%; padding: .45rem .5rem; border-radius: 4px; cursor: pointer; }
    .report-class-picker-option:hover { background: var(--tblr-primary-lt,#e9f2ff); }
    .report-class-picker-option input { margin: 0; }
    .report-print-options .form-hint { display: none; }
    .report-print-options > [class*="col-"] { display: flex; flex-direction: column; align-items: stretch; }
    .report-print-options > [class*="col-"] > .form-label { position: static !important; display: block !important; transform: none !important; height: auto !important; margin: 0 0 .5rem !important; line-height: 1.25 !important; }
    .report-print-options .report-class-picker-toggle { height: 52px; min-height: 52px; padding: 1.25rem 1rem .35rem; border: 1.5px solid #6c5ce7 !important; border-radius: 14px; background: var(--tblr-bg-surface,#fff); color: var(--tblr-body-color); box-shadow: 0 2px 7px rgba(31,41,55,.04); font-size: 1rem; }
    .report-print-options .report-class-picker.is-open .report-class-picker-toggle { border-color: #6c5ce7 !important; }
    .report-student-filter-row .report-filter-toggle { height: 52px; min-height: 52px; padding: 1.25rem 1rem .35rem; border: 1.5px solid #6c5ce7 !important; border-radius: 14px; background: var(--tblr-bg-surface,#fff); color: var(--tblr-body-color); box-shadow: 0 2px 7px rgba(31,41,55,.04); font-size: 1rem; }
    .report-student-filter-row .report-filter-combobox.is-open .report-filter-toggle { border-color: #6c5ce7 !important; }
    .report-student-filter-row .report-filter-field,
    .report-print-options > [class*="col-"] { position: relative; }
    .report-student-filter-row .report-filter-field > .form-label,
    .report-print-options > [class*="col-"] > .form-label { position: absolute !important; z-index: 5; top: .42rem; left: 1rem; margin: 0 !important; padding: 0 .45rem; color: #5b4bd1; background: var(--tblr-bg-surface,#fff); font-size: .72rem; font-weight: 700; line-height: 1.1 !important; pointer-events: none; }
    .report-filter-actions .btn-outline-secondary { background: #2fb344 !important; border-color: #2fb344 !important; color: #fff !important; }
    .report-filter-actions .btn-outline-secondary:hover { background: #269a3a !important; border-color: #269a3a !important; color: #fff !important; }
    .report-filter-actions .btn { height: 52px; min-height: 52px; padding: .5rem 1rem; border-radius: 14px; display: inline-flex; align-items: center; justify-content: center; }
    .report-print-options .form-select { height: 52px; min-height: 52px; padding: 1.25rem 2.25rem .35rem 1rem; border: 1.5px solid #6c5ce7 !important; border-radius: 14px; background: var(--tblr-bg-surface,#fff); color: var(--tblr-body-color); box-shadow: 0 2px 7px rgba(31,41,55,.04); }
    [data-bs-theme="dark"] .report-print-options .form-select,
    body.dark-mode .report-print-options .form-select { border-color: #6c5ce7 !important; }
</style>
@if($type==='student-list')<script>(()=>{const select=document.querySelector('select[name="print_grade_classes[]"]');if(!select)return;const picker=document.createElement('div');picker.className='report-class-picker';const toggle=document.createElement('button');toggle.type='button';toggle.className='report-class-picker-toggle';toggle.innerHTML='<span></span><i class="ti ti-chevron-down"></i>';const menu=document.createElement('div');menu.className='report-class-picker-menu';const search=document.createElement('input');search.type='search';search.className='form-control';search.placeholder='Search Class';const options=document.createElement('div');options.className='report-class-picker-options';const label=toggle.querySelector('span');const sync=()=>{const selected=[...select.options].filter(option=>option.selected).map(option=>option.textContent.trim());label.textContent=selected.join(', ');};[...select.options].forEach(option=>{const row=document.createElement('label');row.className='report-class-picker-option';const checkbox=document.createElement('input');checkbox.type='checkbox';checkbox.value=option.value;checkbox.checked=option.selected;checkbox.addEventListener('change',()=>{option.selected=checkbox.checked;select.dispatchEvent(new Event('change',{bubbles:true}));sync()});row.append(checkbox,document.createTextNode(option.textContent.trim()));options.append(row)});menu.append(search,options);picker.append(toggle,menu);select.classList.add('d-none');select.parentElement.insertBefore(picker,select);toggle.addEventListener('click',event=>{event.stopPropagation();document.querySelectorAll('.report-class-picker.is-open').forEach(other=>{if(other!==picker)other.classList.remove('is-open')});picker.classList.toggle('is-open');if(picker.classList.contains('is-open'))search.focus()});search.addEventListener('input',()=>{const query=search.value.toLowerCase().trim();options.querySelectorAll('.report-class-picker-option').forEach(row=>row.hidden=query&&!row.textContent.toLowerCase().includes(query))});document.addEventListener('click',()=>picker.classList.remove('is-open'));sync()})();</script>@endif
@if($type==='student-list')<script>(()=>{const scope=document.querySelector('select[name="print_scope"]'),select=document.querySelector('select[name="print_grade_classes[]"]');if(!scope||!select)return;const field=select.closest('[class*="col-"]');const update=()=>{const show=scope.value==='selected_classes';field.hidden=!show;if(!show){[...select.options].forEach(option=>{option.selected=false});select.dispatchEvent(new Event('change',{bubbles:true}))}};scope.addEventListener('change',update);update()})();</script>@endif
@endsection
@if($type==='student-list')<script>window.addEventListener('DOMContentLoaded',()=>{const scope=document.querySelector('select[name="print_scope"]');if(!scope)return;const field=document.createElement('div');field.className='col-md-3';field.innerHTML='<label class="form-label">Report Date</label><input type="date" name="report_date" class="form-control" value="{{ $filters['report_date'] ?? now()->format('Y-m-d') }}">';scope.closest('[class*="col-"]').insertAdjacentElement('afterend',field)});</script>@endif
