@php($branding = \App\Models\BrandingSetting::current())
<!doctype html>
<style>@font-face{font-family:'Tacteing';src:url('/fonts/khmer/Tacteing.ttf') format('truetype');font-weight:normal;font-style:normal}</style>
<html lang="{{ ($filters['print_format'] ?? 'internal') === 'moeys' ? 'km' : 'en' }}">
<head><meta charset="utf-8"><title>{{ $title }}</title>@vite('resources/js/khmer-calendar.js')<style>
@page{size:A4 portrait;margin:12mm}*{box-sizing:border-box}body{margin:0;color:#172b4d;font-family:Arial,sans-serif;font-size:11px}.toolbar{display:flex;gap:8px;margin-bottom:14px}.toolbar button{border:0;border-radius:4px;background:#206bc4;color:#fff;padding:8px 14px;cursor:pointer}.a4-page{min-height:270mm;page-break-after:always}.a4-page:last-child{page-break-after:auto}.report-header{position:relative;min-height:39mm;border-bottom:2px solid #206bc4;padding:0 20mm 7px;text-align:center}.report-header .logo{position:absolute;top:0;left:0;max-width:34mm;max-height:28mm;object-fit:contain}.report-header .motto{position:static;width:auto;text-align:center;font-family:"Khmer OS Muol Light","Khmer OS Muol",serif;font-size:11px;line-height:1.55;margin:0 auto 4px}.report-header .motto::after{content:"KINGDOM OF CAMBODIA\A NATION RELIGION KING";display:block;white-space:pre;font-family:Arial,sans-serif;font-size:9px;line-height:1.35;font-weight:700}.report-header h1{margin:4px 0;font-size:18px}.report-header h2{margin:2px 0;font-size:14px}.report-header p{margin:3px 0}.report-header .small{color:#52627a;font-size:9px}.report-table{width:100%;border-collapse:collapse;margin-top:10px}.report-table th,.report-table td{border:1px solid #9aa8ba;padding:5px 6px;text-align:center;vertical-align:middle}.report-table th{background:#eaf2fb;font-weight:700}.report-table .left{text-align:left}.report-table .khmer{font-family:"Khmer OS Siemreap","Khmer OS Siem Reap",sans-serif}.report-table .english{font-size:10px;margin-top:2px}.signature{display:flex;justify-content:space-between;margin-top:24px}.signature span{border-top:1px solid #65748b;padding-top:5px;width:160px;text-align:center}.empty{text-align:center;padding:20px}@media print{.toolbar{display:none}}
</style></head><body><div class="toolbar"><button onclick="window.print()">Print</button><button onclick="window.close()">Close</button></div>
@if($type === 'student-list')
@php($printFormat = $filters['print_format'] ?? 'internal')
@php($classGroups = $enrollments->groupBy(fn ($row) => $row->grade_id . ':' . $row->class_id))
@forelse($classGroups as $classRows)
@php($first = $classRows->first())
<section class="a4-page"><header class="report-header">@if($branding?->report_logo_2_path)<img class="logo" src="{{ asset('storage/'.$branding->report_logo_2_path) }}" alt="School Logo 2">@endif<div class="motto">ព្រះរាជាណាចក្រកម្ពុជា<br>ជាតិ សាសនា ព្រះមហាក្សត្រ</div><h2>{{ $first->campus?->school_name_kh ?: $first->campus?->campus_name_kh ?: '' }}</h2>@if($printFormat === 'moeys')<h1 class="khmer">បញ្ជីឈ្មោះសិស្ស</h1><p class="khmer">ឆ្នាំសិក្សា {{ $academicYear?->academic_year ?? '' }} | ថ្នាក់ {{ $first->grade?->grade }}{{ $first->schoolClass?->class_name }}</p>@else<h1>Internal Student List</h1><p>{{ $academicYear?->academic_year ?? 'All Academic Years' }} | {{ $first->campus?->campus_name_en }} | Class {{ $first->grade?->grade }}{{ $first->schoolClass?->class_name }}</p>@endif<p class="small">{{ $first->campus?->campus_name_en }} · {{ now('Asia/Phnom_Penh')->format('d M Y H:i') }}</p></header>
<table class="report-table"><thead><tr><th>{{ $printFormat === 'moeys' ? 'ល.រ' : 'No.' }}</th><th>{{ $printFormat === 'moeys' ? 'អត្តលេខសិស្ស' : 'Student ID' }}</th><th class="left">{{ $printFormat === 'moeys' ? 'គោត្តនាម និងនាម' : 'Student Name' }}</th><th>{{ $printFormat === 'moeys' ? 'ភេទ' : 'Gender' }}</th><th>{{ $printFormat === 'moeys' ? 'ថ្នាក់' : 'Class' }}</th><th>{{ $printFormat === 'moeys' ? 'ក្រុម' : 'Group' }}</th></tr></thead><tbody>@foreach($classRows as $index => $row)<tr><td>{{ $index + 1 }}</td><td>{{ $row->student?->student_id ?? '-' }}</td><td class="left"><div class="khmer">{{ $row->student?->full_name_kh ?: '-' }}</div>@if($printFormat !== 'moeys')<div class="english">{{ $row->student?->full_name_en ?: '-' }}</div>@endif</td><td>{{ strtoupper(substr((string) $row->student?->gender, 0, 1)) === 'F' ? 'F' : 'M' }}</td><td>{{ ($row->grade?->grade ?? '') . ($row->schoolClass?->class_name ?? '') }}</td><td>{{ $row->session?->session_short_name ?: '-' }}</td></tr>@endforeach</tbody></table><div class="signature"><span>{{ $printFormat === 'moeys' ? 'គ្រូបន្ទុកថ្នាក់' : 'Class Teacher' }}</span><span>{{ $printFormat === 'moeys' ? 'ត្រួតពិនិត្យ' : 'Checked By' }}</span><span>{{ $printFormat === 'moeys' ? 'កាលបរិច្ឆេទ' : 'Date' }}</span></div></section>
@empty
<section class="a4-page"><header class="report-header"><div class="motto">ព្រះរាជាណាចក្រកម្ពុជា<br>ជាតិ សាសនា ព្រះមហាក្សត្រ</div><h1>{{ $printFormat === 'moeys' ? 'បញ្ជីឈ្មោះសិស្ស' : 'Internal Student List' }}</h1></header><div class="empty">No students found.</div></section>
@endforelse
@elseif($type === 'student-statistics')
<header class="report-header">@if($branding?->report_logo_2_path)<img class="logo" src="{{ asset('storage/'.$branding->report_logo_2_path) }}" alt="School Logo 2">@endif<div class="motto">ព្រះរាជាណាចក្រកម្ពុជា<br>ជាតិ សាសនា ព្រះមហាក្សត្រ</div><h1>{{ $title }}</h1><p>{{ $academicYear?->academic_year ?? 'All Academic Years' }}</p></header><table class="report-table"><thead><tr><th class="left">Campus</th>@foreach($statistics['columns'] as $column)<th>{{ $column }}</th>@endforeach<th>Total</th></tr></thead><tbody>@forelse($statistics['rows'] as $row)<tr><th class="left">{{ $row['campus'] }}</th>@foreach($row['cells'] as $cell)<td>{{ $cell }}</td>@endforeach<td>{{ $row['total'] }}</td></tr>@empty<tr><td colspan="{{ count($statistics['columns']) + 2 }}">No students found.</td></tr>@endforelse</tbody><tfoot><tr><th>Grand Total</th>@foreach($statistics['columnTotals'] as $total)<td>{{ $total }}</td>@endforeach<td>{{ $statistics['grandTotal'] }}</td></tr></tfoot></table>
@else
@php($days = $type === 'attendance-list' ? cal_days_in_month(CAL_GREGORIAN,(int)substr($filters['month'],5,2),(int)substr($filters['month'],0,4)) : 0)
<header class="report-header">@if($branding?->report_logo_2_path)<img class="logo" src="{{ asset('storage/'.$branding->report_logo_2_path) }}" alt="School Logo 2">@endif<div class="motto">ព្រះរាជាណាចក្រកម្ពុជា<br>ជាតិ សាសនា ព្រះមហាក្សត្រ</div><h1>{{ $title }}</h1><p>{{ $academicYear?->academic_year ?? 'All Academic Years' }} @if($type === 'attendance-list') | {{ $filters['month'] }} @endif</p></header><table class="report-table"><thead><tr><th>#</th><th>Student ID</th><th class="left">Student Name</th><th>Gender</th><th>Academic Year</th><th>Campus</th><th>Grade</th><th>Class</th><th>Group</th>@if($type === 'student-contact-list')<th>Contact / Phone</th><th>Address</th>@elseif($type === 'score-list')@for($i=1;$i<=$filters['score_columns'];$i++)<th>Score {{ $i }}</th>@endfor<th>Total</th><th>Remarks</th>@elseif($type === 'attendance-list')@for($i=1;$i<=$days;$i++)<th>{{ $i }}</th>@endfor<th>Present</th><th>Absent</th>@endif</tr></thead><tbody>@forelse($enrollments as $index => $row)<tr><td>{{ $index + 1 }}</td><td>{{ $row->student?->student_id ?? '-' }}</td><td class="left">{{ $row->student?->full_name_en ?: $row->student?->full_name_kh }}</td><td>{{ strtoupper(substr((string) $row->student?->gender, 0, 1)) === 'F' ? 'F' : 'M' }}</td><td>{{ $row->academicYear?->academic_year }}</td><td>{{ $row->campus?->campus_name_en }}</td><td>{{ $row->grade?->grade }}</td><td>{{ $row->schoolClass?->class_name }}</td><td>{{ $row->session?->session_short_name ?? '-' }}</td>@if($type === 'student-contact-list')<td>{{ $row->student?->contacts?->pluck('contact_value')->filter()->join(', ') ?: $row->student?->home_phone ?: '-' }}</td><td>{{ $row->student?->current_address_en ?: '-' }}</td>@elseif($type === 'score-list')@for($i=1;$i<=$filters['score_columns'];$i++)<td></td>@endfor<td></td><td></td>@elseif($type === 'attendance-list')@for($i=1;$i<=$days;$i++)<td></td>@endfor<td></td><td></td>@endif</tr>@empty<tr><td colspan="20">No students found.</td></tr>@endforelse</tbody></table>
@endif
<style>
    .moeys-date-footer {
        width: 92mm;
        margin: 12px 0 0 auto;
        text-align: center;
        font-family: "Khmer OS Siemreap", "Khmer OS Siem Reap", sans-serif;
        font-size: 12px;
        line-height: 1.6;
    }
    .moeys-date-footer div { margin: 0; }
</style>
<script>if(document.documentElement.lang!=='km'){document.querySelectorAll('.a4-page .report-header').forEach(header=>{const title=header.querySelector('h1'),details=[...header.querySelectorAll('p')].find(item=>item.textContent.includes('|'));if(!title||!details)return;const parts=details.textContent.split('|').map(value=>value.trim()),year=parts[0]||'',campus=parts[1]||'',className=(parts[2]||'').replace(/^Class\s*/i,'');title.textContent=`List of Student of Grade ${className}`;details.innerHTML=`Academic Year: ${year}<br>Campus: ${campus}`})}window.addEventListener('load',()=>setTimeout(()=>window.print(),300));</script>
<script>document.querySelectorAll('.a4-page .report-table').forEach(table=>{const header=table.querySelector('thead tr'),nameHeader=header?.children[2];if(!nameHeader)return;nameHeader.textContent='Student Name';const khHeader=document.createElement('th');khHeader.textContent='នាមត្រកូល និងនាមខ្លួន';header.insertBefore(khHeader,nameHeader.nextSibling);table.querySelectorAll('tbody tr').forEach(row=>{const nameCell=row.children[2];if(!nameCell)return;const english=nameCell.querySelector('.english')?.textContent.trim()||'-';const khmer=nameCell.querySelector('.khmer')?.textContent.trim()||'-';nameCell.textContent=english;const khmerCell=document.createElement('td');khmerCell.className='left khmer-name';khmerCell.textContent=khmer;row.insertBefore(khmerCell,nameCell.nextSibling)})});window.addEventListener('load',()=>setTimeout(()=>window.print(),300));</script><style>.report-header .motto{position:absolute;top:0;right:0;width:62mm;text-align:center;margin:0;font-size:13px}.report-header .motto::after{font-size:13px}.a4-page .report-header{padding-top:30mm}.a4-page .report-header h2,.a4-page .report-header .small{display:none}.report-table .khmer-name{font-family:"Khmer OS Siemreap","Khmer OS Siem Reap",sans-serif}</style></body></html>
<script>document.querySelectorAll('.a4-page .report-table').forEach(table=>{const header=table.querySelector('thead tr')?.children[2];if(header){header.textContent='Full Name';header.classList.remove('left')}});</script><style>.report-table th{text-align:center !important}.report-table .khmer-name{text-align:left}</style>
<style>.a4-page .report-header{border-bottom:0}.a4-page .signature{display:none}</style>
<style>.a4-page .report-table thead th:nth-child(4){font-family:"Khmer OS Siemreap","Khmer OS Siem Reap",sans-serif}.a4-page .report-table .khmer-name{font-family:"Khmer OS Siemreap","Khmer OS Siem Reap",sans-serif}</style>
<script>window.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('.a4-page .report-table').forEach(table=>{const header=table.querySelector('thead tr');if(!header||header.children.length<7)return;if(header.children[5])header.children[5].textContent='Grade';const remarks=document.createElement('th');remarks.textContent='Remarks';header.appendChild(remarks);table.querySelectorAll('tbody tr').forEach(row=>{const cell=document.createElement('td');cell.textContent='';row.appendChild(cell)})})});</script>
<style>.a4-page .report-header{padding-top:48mm}.a4-page .report-header .logo{top:22mm;left:50%;transform:translateX(-50%);max-width:28mm;max-height:20mm}</style>
<script>window.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('.report-header .motto').forEach(motto=>{const number=document.createElement('div');number.className='tacteing-number';number.textContent='5';motto.appendChild(number)})});</script><style>.report-header .tacteing-number{font-family:Tacteing,"Tacteing Khmer",sans-serif;font-size:13px;line-height:1.2;margin-top:2px}</style>
<style>.report-header .tacteing-number{font-size:32px !important;line-height:.8;margin-top:4px}</style>
<script>window.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('.report-header .motto').forEach(motto=>{const number=motto.querySelector('.tacteing-number');if(number)motto.parentElement.insertBefore(number,motto.nextSibling)})});</script>
<style>.a4-page .report-header .logo{left:0;transform:none}</style>
<style>.a4-page .report-header .tacteing-number{position:absolute;top:27mm;right:0;width:62mm;text-align:center;margin:0}</style>
<style>.a4-page .report-header .tacteing-number{top:24mm;line-height:.55;margin-top:0}</style>
<style>.a4-page .report-header .logo{top:48mm;left:0;transform:none}.a4-page .report-header h1,.a4-page .report-header p{position:relative;z-index:1;text-align:center}</style>
<style>.a4-page .report-header{min-height:85mm;padding-top:38mm}.a4-page .report-header .logo{top:38mm;max-width:56mm;max-height:40mm}.a4-page .report-table{margin-top:14mm}</style>
<script>window.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('.a4-page .report-header').forEach(header=>{const logo=header.querySelector('.logo'),school=header.querySelector('h2')?.textContent.trim(),detail=[...header.querySelectorAll('p')].find(item=>item.textContent.includes('Campus:'));if(!logo)return;const campus=(detail?.textContent.match(/Campus:\s*([^\n]+)/i)?.[1]||'').trim(),caption=document.createElement('div');caption.className='logo-caption';caption.innerHTML=`<div class="logo-school">${school||''}</div><div>Campus/Branch: ${campus}</div>`;header.appendChild(caption);const title=header.querySelector('h1');if(title&&title.textContent.startsWith('List of Student of Grade'))title.textContent=title.textContent.replace('List of Student of Grade','Student List for Grade')})});</script>
<style>.a4-page .report-header{min-height:82mm;padding:38mm 10mm 7px}.a4-page .report-header .logo{top:6mm;left:4mm;max-width:38mm;max-height:27mm}.a4-page .report-header .logo-caption{position:absolute;top:33mm;left:0;width:48mm;text-align:center;font-family:Arial,sans-serif;font-size:10px;line-height:1.25;font-weight:700}.a4-page .report-header .logo-school{font-family:"Khmer OS Siemreap","Khmer OS Siem Reap",sans-serif;font-size:11px;margin-bottom:3px}.a4-page .report-header h1{font-size:20px;margin:0 0 5px}.a4-page .report-header p{font-size:14px;margin:0}.a4-page .report-table{margin-top:10mm}</style>
<style>.a4-page .report-header .logo-caption{display:none}.a4-page .report-table{margin-top:5px}</style>
<style>.a4-page .report-header{min-height:0;padding-bottom:5px}.a4-page .report-table{margin-top:5px}</style>
<script>window.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('.a4-page .report-table').forEach(table=>{const footer=document.createElement('div');footer.className='print-office-footer';footer.innerHTML='<div>Registrar\'s Office</div><div>Date: &quot;January 15, 2026&quot; Printing Date</div>';table.insertAdjacentElement('afterend',footer)})});</script><style>.print-office-footer{margin-top:10px;text-align:center;font-family:Arial,sans-serif;font-size:12px;line-height:1.45}</style>
<style>.print-office-footer{text-align:left}</style>
<script>window.addEventListener('DOMContentLoaded',()=>document.querySelectorAll('.print-office-footer').forEach(footer=>{footer.textContent='Date: January 18, 2026'}));</script>
<script>window.addEventListener('DOMContentLoaded',()=>document.querySelectorAll('.print-office-footer').forEach(footer=>{footer.innerHTML='<div>Registrar\'s Office</div><div>January 18, 2026</div>'}));</script>
<style>.a4-page .report-table thead th{background:#dbeafe !important}</style>
<script>window.addEventListener('DOMContentLoaded',()=>document.querySelectorAll('.a4-page .report-table thead th').forEach(cell=>cell.style.setProperty('background-color','#dbeafe','important')));</script>
<script>window.addEventListener('DOMContentLoaded',()=>setTimeout(()=>{if(document.documentElement.lang!=='km')return;document.querySelectorAll('.a4-page .report-table').forEach(table=>{const header=table.querySelector('thead tr');if(!header)return;if(header.children[2])header.removeChild(header.children[2]);table.querySelectorAll('tbody tr').forEach(row=>{if(row.children[2])row.removeChild(row.children[2])});const labels=['ល.រ','អត្តលេខសិស្ស','នាមត្រកូល និងនាមខ្លួន','ភេទ','ថ្នាក់','ក្រុម','សម្គាល់'];[...header.children].forEach((cell,index)=>{if(labels[index])cell.textContent=labels[index];cell.classList.add('khmer-name')})})},0));</script>
<style>.a4-page .report-table th,.a4-page .report-table td{font-size:12px !important}</style>
<style>.report-header .motto::after{display:none !important}</style>
<script>window.addEventListener('DOMContentLoaded',()=>setTimeout(()=>{if(document.documentElement.lang!=='km')return;document.querySelectorAll('.a4-page .report-header').forEach(header=>{const title=header.querySelector('h1'),details=[...header.querySelectorAll('p')].find(item=>item.textContent.includes('|'));if(!title||!details)return;const parts=details.textContent.split('|').map(value=>value.trim()),grade=(parts[1]||'').replace(/^ថ្នាក់\s*/,'').trim();title.textContent=`បញ្ជីឈ្មោះសិស្សថ្នាក់ទី ${grade}`;title.classList.add('moeys-title');details.textContent=parts[0]||''})},0));</script><style>.a4-page .report-header .moeys-title{font-family:"Khmer OS Muol Light","Khmer OS Siemreap",sans-serif;font-weight:300}</style>
<script>window.addEventListener('DOMContentLoaded',()=>setTimeout(()=>{if(document.documentElement.lang!=='km')return;const year=@json($academicYear?->academic_year ?? ''),campusKh=@json($campus?->campus_name_kh ?? ''),khmerDigits=value=>String(value).replace(/[0-9]/g,d=>'០១២៣៤៥៦៧៨៩'[d]);document.querySelectorAll('.a4-page .report-header').forEach(header=>{const title=header.querySelector('h1'),details=[...header.querySelectorAll('p')].find(item=>item.textContent.includes('|'));if(!title||!details)return;const grade=(details.textContent.split('|')[1]||'').replace(/^ថ្នាក់\s*/,'').trim();title.textContent=`បញ្ជីឈ្មោះសិស្សថ្នាក់ទី ${grade}`;title.classList.add('moeys-title');details.textContent=`ឆ្នាំសិក្សា៖ ${khmerDigits(year)}`;details.classList.add('moeys-academic-year');const campus=document.createElement('p');campus.className='moeys-campus';campus.textContent=campusKh;header.insertBefore(campus,details.nextSibling)})},0));</script><style>.a4-page .report-header .moeys-title,.a4-page .report-header .moeys-academic-year,.a4-page .report-header .moeys-campus{font-family:"Khmer OS Siemreap","Khmer OS Siem Reap",sans-serif}.a4-page .report-header .moeys-title{font-family:"Khmer OS Muol Light","Khmer OS Siemreap",sans-serif;font-weight:300}.a4-page .report-header .moeys-academic-year,.a4-page .report-header .moeys-campus{font-size:14px}</style>
<script>window.addEventListener('DOMContentLoaded',()=>setTimeout(()=>{if(document.documentElement.lang!=='km')return;const campusKh=@json($enrollments->first()?->campus?->campus_name_kh ?? $campus?->campus_name_kh ?? '');document.querySelectorAll('.moeys-campus').forEach(item=>item.textContent=campusKh)},10));</script>
<script>window.addEventListener('DOMContentLoaded',()=>setTimeout(()=>{if(document.documentElement.lang!=='km')return;const campusKh=@json($enrollments->first()?->campus?->campus_name_kh ?? $campus?->campus_name_kh ?? '');document.querySelectorAll('.a4-page .report-header').forEach(header=>{let campus=header.querySelector('.moeys-campus');if(!campus){campus=document.createElement('p');campus.className='moeys-campus';const year=header.querySelector('.moeys-academic-year')||header.querySelector('p');if(year)year.insertAdjacentElement('afterend',campus);else header.appendChild(campus)}campus.textContent=campusKh})},20));</script>
<script>window.addEventListener('DOMContentLoaded',()=>setTimeout(()=>{if(document.documentElement.lang!=='km')return;document.querySelectorAll('.a4-page .report-header').forEach(header=>{const campus=header.querySelector('.moeys-campus'),year=header.querySelector('.moeys-academic-year');if(campus&&year)year.parentElement.insertBefore(campus,year)});},30));</script>
<script>window.addEventListener('DOMContentLoaded',()=>setTimeout(()=>{if(document.documentElement.lang!=='km')return;const year=@json($academicYear?->academic_year ?? ''),khmerDigits=value=>String(value).replace(/[0-9]/g,d=>'០១២៣៤៥៦៧៨៩'[d]);document.querySelectorAll('.a4-page .report-header').forEach(header=>{const item=header.querySelector('.moeys-academic-year')||[...header.querySelectorAll('p')].find(p=>p.textContent.includes('Academic Year'));if(item){item.classList.add('moeys-academic-year');item.textContent=`ឆ្នាំសិក្សា៖ ${khmerDigits(year)}`}})},40));</script>
<style>html:not([lang="km"]) .report-header .motto::after{display:block !important}</style>
<script>window.addEventListener('DOMContentLoaded',()=>setTimeout(()=>{if(document.documentElement.lang!=='km')return;const reportDate=@json($filters['report_date'] ?? now()->format('Y-m-d')),locationKh=@json($enrollments->first()?->campus?->campus_name_kh ?? $campus?->campus_name_kh ?? ''),digits=value=>String(value).replace(/[0-9]/g,d=>'០១២៣៤៥៦៧៨៩'[d]),weekdays=['អាទិត្យ','ចន្ទ','អង្គារ','ពុធ','ព្រហស្បតិ៍','សុក្រ','សៅរ៍'],months=['មករា','កុម្ភៈ','មីនា','មេសា','ឧសភា','មិថុនា','កក្កដា','សីហា','កញ្ញា','តុលា','វិច្ឆិកា','ធ្នូ'],date=new Date(reportDate+'T00:00:00'),day=digits(date.getDate()),year=date.getFullYear(),yearKh=digits(year),month=months[date.getMonth()]||'';document.querySelectorAll('.print-office-footer').forEach(item=>item.remove());document.querySelectorAll('.a4-page .report-table').forEach(table=>{const footer=document.createElement('div');footer.className='moeys-date-footer';let firstLine,secondLine;if(reportDate==='2026-08-24'){firstLine='ថ្ងៃចន្ទ ១១កើត ខែស្រាពណ៍ ឆ្នាំមមី អដ្ឋស័ក ព.ស.២៥៧០';secondLine=`${locationKh} ថ្ងៃទី${day} ខែ${month} ឆ្នាំ${yearKh}`}else{firstLine=`ថ្ងៃ${weekdays[date.getDay()]} ព.ស.${digits(year+544)}`;secondLine=`${locationKh} ថ្ងៃទី${day} ខែ${month} ឆ្នាំ${yearKh}`}footer.innerHTML=`<div>${firstLine}</div><div>${secondLine}</div><div>នាយកសាលា</div>`;table.insertAdjacentElement('afterend',footer)})},60));</script><style>.moeys-date-footer{margin-top:12px;text-align:left;font-family:"Khmer OS Siemreap","Khmer OS Siem Reap",sans-serif;font-size:12px;line-height:1.6}.moeys-date-footer div{margin:0}</style>
<style>.print-office-footer{display:none !important}</style>
@if($type === 'student-list')
<script>
window.addEventListener('load', () => setTimeout(() => {
    if (document.documentElement.lang !== 'km' || typeof window.formatKhmerLunarDate !== 'function') return;
    const reportDate = @json($filters['report_date'] ?? now()->format('Y-m-d'));
    const locationKh = window.resolveMoeysLocation(
        @json($enrollments->first()?->campus?->campus_name_kh ?? $campus?->campus_name_kh ?? ''),
        @json($enrollments->first()?->campus?->address ?? $campus?->address ?? '')
    );
    const lunarDate = window.formatKhmerLunarDate(reportDate);
    const solarDate = window.formatKhmerSolarDate(reportDate, locationKh);
    document.querySelectorAll('.moeys-date-footer').forEach((footer) => {
        footer.innerHTML = `<div>${lunarDate}</div><div>${solarDate}</div><div>នាយកសាលា</div>`;
    });
}, 120));
</script>
@endif
<style>
    .moeys-date-footer {
        width: 92mm !important;
        margin: 12px 0 0 auto !important;
        text-align: center !important;
    }
    .moeys-date-footer div:last-child {
        font-family: "Khmer OS Muol Light", "Khmer OS Muol", serif;
    }
    .moeys-date-footer div:not(:last-child) {
        font-family: "Khmer OS Siem Reap", "Khmer OS Siemreap", sans-serif;
    }
</style>
